### ISSUE TITLE
Python-CFFI ドキュメントに複数の誤字がある

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#104]
> **Aternatively**, on OS/X 10.6 (Thanks Juraj Sukop for this)
> https://cffi.readthedocs.io/en/latest/installation.html

`Aternatively` → `Alternatively`

>  This is because most C libraries are **intented** for, and tested with, a situation 
> https://cffi.readthedocs.io/en/latest/installation.html

`intented` → `intended`

> In previous versions, this could be achieved using uint16_t and int32_t but without automatic **convertion** to Python unicodes.
> https://cffi.readthedocs.io/en/latest/using.html

`convertion` → `conversion`

**Comment by cosmo0920** [comment]
Pull-req送った。 https://bitbucket.org/cffi/cffi/pull-requests/84/fix-typo/diff
