### ISSUE TITLE
Cython: ドキュメントにタイポがある

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#105]
> They should generally be preferred over plain integers to improve **readabilty.**
> http://docs.cython.org/en/latest/src/reference/extension_types.html

`readabilty` → `readability`

> This does slightly more than providing a python wrapper for a cdef method: unlike a cdef method, a cpdef method is fully **overrideable** by methods and instance attributes in Python subclasses. It adds a little calling overhead compared to a cdef method.
> http://docs.cython.org/en/latest/src/tutorial/cdef_classes.html

`overrideable` → `overridable`

**Comment by ashie** [comment]
githubにリポジトリがあるはず

**Comment by ashie** [comment]
* https://github.com/cython/cython/blob/master/docs/src/reference/extension_types.rst
* https://github.com/cython/cython/blob/master/docs/src/tutorial/cdef_classes.rst

**Comment by ashie** [comment]
コミットメッセージを書くのに当たり、過去のコミットログを見ていて面白いコミットを見つけた

```
commit 4f237620217c458a299304a60361cd40e195b190
Author: Unknown <kunda@scribus.net>
Date:   Tue Oct 17 13:00:00 2017 -0400

    Trivial typo fixes
    
    Most are non-user facing.
    Found using:
    `codespell -d -q 3`
```

codespellというコマンドは初めて知った。
手元のコードを色々チェックしてみたが、続々typoが見つかる。

**Comment by ashie** [comment]
ちなみに今回のtypoはいずれもcodespellでは検出できなかった。

**Comment by ashie** [comment]
プルリク送った https://github.com/cython/cython/pull/2062
