### ISSUE TITLE
Perconaのサイトでダウンロードできる percona-release のバージョンが古い

### ISSUE THREAD

**Issue by komainu8** [clear-code/statistics#106]
以下のURLでは、0.1-4 がlatest となっているが、0.1-5が存在しているので以下のURLの内容の更新漏れと思われる。
http://www.percona.com/downloads/percona-release/redhat/ 

0.1-5は以下の場所にある。
http://repo.percona.com/release/7/RPMS/noarch/
http://repo.percona.com/release/6/RPMS/noarch/

**Comment by okkez** [comment]
https://twitter.com/percona があるので、ここにメンションすればよさそう。
もしくは https://github.com/percona/percona-repositories があるのでここに issue をたてるか。

**Comment by cosmo0920** [comment]
https://jira.percona.com/secure/Dashboard.jspa にあったりしません？

**Comment by okkez** [comment]
う、メンションしてしまった。。。

**Comment by okkez** [comment]
perona-release で検索してみたけど、該当するissueはなさそうだった。

**Comment by komainu8** [comment]
既に報告済みのため、closeします。
