### ISSUE TITLE
redmine: コロンを含む文字列をうまくリンクできない

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#108]
### 現象

タイトルにコロンを含む場合にうまく内部リンクできない。

### 再現手順

1. Redmineのコメント欄に次の入力を加える

```
[[a:bc]]
[[xyz]]
```

2. 投稿すると次のような表示になる

![2018-01-11-100432_245x100_scrot](https://user-images.githubusercontent.com/8974561/34803505-07068012-f6b7-11e7-9495-a484617d86ee.png)

**Comment by ashie** [comment]
そういう仕様だと思う（プロジェクトへのリンクになる）けど、エスケープできないのかな?

http://redmine.jp/tech_note/RedmineWikiFormatting/

**Comment by fujimotos** [comment]
仕様なんですね。ありがとうございます。
