### ISSUE TITLE
man: iconv(3)の翻訳にtypoがあった

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#109]
## Problem

http://linuxjm.osdn.jp/html/LDP_man-pages/man3/iconv.3.html にtypoをみつけた。

## Actual

```
 iconv() 関数は 1 度に 1 つのマルチバイト文字を変換する。(略) 入力の文字エンコーディングがが状態を持つ場合、 (略)
```

## Expected

```
 iconv() 関数は 1 度に 1 つのマルチバイト文字を変換する。(略) 入力の文字エンコーディングが状態を持つ場合、 (略)
```

「入力の文字エンコーディング**がが**」ではなく「入力の文字エンコーディング**が**」となっていること。

**Comment by okkez** [comment]
http://linuxjm.osdn.jp/ の下の方にバグレポートを送るメールアドレスが書いてあった。

**Comment by okkez** [comment]
書かれていたメールアドレスにメールを送った。URLが無いので開いたままにしておく。

**Comment by okkez** [comment]
https://ja.osdn.net/projects/linuxjm/lists/archive/discuss/2018-January/001383.html

MLのアーカイブを見つけることができたので閉じる。
