### ISSUE TITLE
rspamd: /etc/init.d/rspamdがなくなった/etc/rspamd/rspamd.sysvinit.confを参照している？

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#110]
ちゃんと確認していないけど、Rspamd本家がt提供しているCentOS 6のRPMパッケージが前は`/etc/rspamd/rspamd.sysvinit.conf`を提供していたけど、最近のパッケージだと`/etc/rspamd/rspamd.conf`だけ提供するように変わっているんだけど、`/etc/init.d/rspamd`では`/etc/rspamd/rspamd.sysvinit.conf`を参照するままになっていてサービスの起動に失敗している気がする。

**Comment by cosmo0920** [comment]
報告した。 https://github.com/vstakhov/rspamd/issues/2044
