### ISSUE TITLE
fluent-plugin-elasticsearch: READMEにElasticSearch表記が残っている

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#111]
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.md

Elasticsearch（sが小文字）が正式表記。

https://github.com/elastic/elasticsearch/issues/4634

**Comment by piroor** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/pull/349 PRを作成しました。以後はそちらでトラックされるため、こちらはCloseします。

**Comment by cosmo0920** [comment]
v0.12向けのブランチもメンテナンスしているのでv0.12ブランチにも修正がほしいです。
