### ISSUE TITLE
tdiary-style-markdown: *...*で強調表示にならないことがある

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#112]
前後にスペースがないとダメになっている気がする。

たとえば以下だとダメ。

```markdown
後半の第5章から第7章は*「開発やメンテナンスにおける、チーム内での良いコミュニケーション」*をテーマにしています。
```

**Comment by piroor** [comment]
https://github.com/clear-code/tdiary-style-markdown
→ https://github.com/gjtorikian/commonmarker
→ https://github.com/github/cmark

依存関係を辿るとこのようになっている。どこの問題か？

**Comment by piroor** [comment]
github/cmark は commonmark/cmark の改造版。
commonmark/cmark に問題があった場合でも、tdiary-style-markdownでの使用という観点では、 commonmark/cmark に直接報告するよりは、一旦github/cmarkに報告し、GitHubのチームがcommonmark/cmarkにフィードバックしてくれるのを待つのがよい。

**Comment by piroor** [comment]
commonmarkerで`<em>`タグを出力している箇所
https://github.com/gjtorikian/commonmarker/blob/master/ext/commonmarker/html.c#L338
これは`cmark_node`型の引数のプロパティ（メンバー変数？）に対するマッチング。
https://github.com/github/cmark/blob/master/src/html.c
cmarkに全く同じコードがあるので、github/cmark由来の部分と思われる。
よって、フィードバックはgithub/cmarkに行う。

**Comment by piroor** [comment]
github/cmarkでは期待通りの結果になった。

```
$ git clone https://github.com/github/cmark.git
$ cd cmark
$ make
$ echo "foo *bar* bazz" | build/src/cmark-gfm 
<p>foo <em>bar</em> bazz</p>
$ echo "日本語のテキストの*一部分*を協調" | build/src/cmark-gfm 
<p>日本語のテキストの<em>一部分</em>を協調</p>
```

commonmarkerが使っているcmarkが古い？

**Comment by piroor** [comment]
例示されている文章だとうまくいかない。

```
$ echo "後半の第5章から第7章は*開発やメンテナンスにおける、チーム内での良いコミュニ ケーション*をテーマにしています。"  | build/src/cmark-gfm 
<p>後半の第5章から第7章は<em>開発やメンテナンスにおける、チーム内での良いコミュニケーション</em>をテーマにしています。</p>
$ echo "後半の第5章から第7章は*「開発やメンテナンスにおける、チーム内での良いコミュ ニケーション*をテーマにしています。"  | build/src/cmark-gfm 
<p>後半の第5章から第7章は*「開発やメンテナンスにおける、チーム内での良いコミュニケーション*をテーマにしています。</p>
```

禁則処理のように、協調してよい場合とそうでない場合を判別しているようだ。

**Comment by piroor** [comment]
`「`の文字コードは`\u300c`、10進数で`12300`。
https://github.com/github/cmark/blob/master/src/utf8.c#L288 の1つ目の条件にあてはまっている。
詳細はまだ分かっていないが、`「」`を囲う形の強調はできないように敢えて設計されているという事のように思われる。

**Comment by piroor** [comment]
cmarkのtest/spec.txtに以下のような記述がある。

```
This is not emphasis, because the opening `*` is preceded
by an alphanumeric and followed by punctuation, and hence
not part of a [left-flanking delimiter run]:

```````````````````````````````` example
a*"foo"*
.
<p>a*&quot;foo&quot;*</p>
````````````````````````````````

```

`「`がpunctuationの一種として定義されていることから、このパターンに当てはまっているように思われる。

**Comment by piroor** [comment]
https://github.com/github/cmark/issues/80 に報告したのでこちらはcloseします。

**Comment by piroor** [comment]
https://github.com/commonmark/cmark/pull/208
実装のバグではなく仕様のバグとして議論が進んでいる模様です。
