### ISSUE TITLE
Fedora 27: Virtualboxでのインストールに失敗する

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#114]
### 再現手順

1. https://getfedora.org/ からFedora 27 (Server Edition) のイメージをダウンロードする
2. Virtualboxに仮想マシンを用意して、Fedoraのイメージを起動する
3. 「インストール時に使用する言語： 日本語 > 日本語（日本）」を選択し、手順を進める

### 発生する不具合

インストール完了直前にインストーラがクラッシュして、正常にインストールが完了しない

ちなみに、言語を英語にすると正常にインストールできる。

### 再現環境

次の環境で再現を確認：

1. Fedora-Server-dvd-x86_64-27-1.6.iso
2. Virtualbox Version 5.1.30_Debian r118389

### スクリーンショット

![2018-01-26-123733_1149x470_scrot](https://user-images.githubusercontent.com/8974561/35424346-609ed364-0296-11e8-894f-d009209b86ea.png)

**Comment by okkez** [comment]
ISO抜いてそのまま再起動したら使えるみたい。

**Comment by okkez** [comment]
似てるけど違った。
https://bugzilla.redhat.com/show_bug.cgi?id=1517141

報告した。
https://bugzilla.redhat.com/show_bug.cgi?id=1540053

**Comment by fujimotos** [comment]
ありがとうございます！
