### ISSUE TITLE
Zulip: カスタム絵文字追加画面の日本語翻訳がおかしい

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#12]
「●●組織のメンバー用の追加の絵文字を追加します。」

「追加」が2回もでるのは変。

**Comment by piroor** [comment]
原文は「Add extra emoji for members of the __realm_name__ organization.」なので確かに多いですね

**Comment by cosmo0920** [comment]
プリセットでない絵文字を追加しますということを言いたいんでしょうけれど、追加する絵文字は基本的に初期状態ではないやつなので省略してもいいのかもと思いました。

**Comment by kou** [comment]
フィードバック先： https://www.transifex.com/zulip/zulip/language/ja/

**Comment by piroor** [comment]
ちがった、多くなかった。「add」と「extra」がどちらも「追加」と訳されているから違和感があるんですね。「●●組織のメンバー専用の絵文字を追加します」あたりだと違和感がなさそうな気がします。

**Comment by kenhys** [comment]
> 「●●組織のメンバー専用の絵文字を追加します」

をフィードバックしてみました。

メモ: チームにjoinしないとフィードバックできない模様。
