### ISSUE TITLE
meta-browserのFirefoxを52ESRに更新したい

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#121]
ちょっとここでやるには重すぎるかもしれないが、試しに登録してみる。

[meta-browser](https://github.com/OSSystems/meta-browser)のFirefoxが45ESRで古いままなので、更新したい。

作業はある程度は進んでいて、ちょっと古いものの以下のブランチで動作は確認できている

* https://github.com/ashie/meta-browser/commit/4bc76e3b7c55723d08646f2d0dab83de52eca3e7#diff-e95b855f73f2342c35e96e32185aecdd

が、いくつか問題があるのでアップストリームに還元できていない。

* Skiaだと描画が乱れる。Cairoに切り替えると正常に描画できる。
    * `gfx.content.azure.backends`と`gfx.canvas.azure.backends`を`skia`から`cairo`に
* musl対応ができていない
    * もたもたしている間にupstreamでmuslに対応するためのパッチが入ってしまったが、52ESRの方では対応できていない
    * https://github.com/OSSystems/meta-browser/blob/7ee6612e0aec2c0fd4021577514f9590b1be11b1/recipes-browser/firefox/firefox_45.9.0esr.bb#L48
* l10nのインストールパスが間違っていたかもしれないが記憶があやふや

あと少し時間が経ってしまったので各種パッチ（debianパッチとupstreamのパッチ）を更新する必要があるかもしれない。

動作確認は以下の方法で

* http://www.clear-code.com/blog/2018/1/9.html

参考情報として、途中版でお伺いを立てたときのPR

* https://github.com/OSSystems/meta-browser/pull/43

**Comment by cosmo0920** [comment]
https://github.com/OSSystems/meta-browser/pull/106 muslはChromiumに関しても削除されたようなのでmusl対応をしなくても良さそう

**Comment by cosmo0920** [comment]
まずは軽くお伺いをたてるということで、muslサポートをfirefoxから削るPRを出しました。
https://github.com/OSSystems/meta-browser/pull/117

**Comment by cosmo0920** [comment]
muslサポートを外すことに成功しました。 :muscle:

**Comment by cosmo0920** [comment]
https://github.com/OSSystems/meta-browser/pull/121 更新できたのでクローズします。 😤💪 🎉
