### ISSUE TITLE
rabbit-shocker.org の説明の文章を改善したい

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#123]
https://rabbit-shocker.org/ja/how-to-make/ の footnote に以下の文章がある。

> PDF形式の場合も変更できま すが、多くの部分はPDFでレイアウト済みなので変更できるは部分 的になります。

以下が正しいのでは？

> PDF形式の場合も変更できま すが、多くの部分はPDFでレイアウト済みなので変更できるのは部分的になります。

upstream は https://github.com/rabbit-shocker のどれかのリポジトリのはず。

**Comment by cosmo0920** [comment]
報告した。 https://github.com/rabbit-shocker/rabbit/pull/113
