### ISSUE TITLE
WebKitGTK+: typo in document

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#13]
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebInspector.html#WebKitWebInspector.description の

```c
/* Enable the developer extras */
WebKitSettings *setting = webkit_web_view_get_settings (WEBKIT_WEB_VIEW(my_webview));
g_object_set (G_OBJECT(settings), "enable-developer-extras", TRUE, NULL);

/* Load some data or reload to be able to inspect the page*/
webkit_web_load_uri (WEBKIT_WEB_VIEW(my_webview), "http://www.gnome.org");

/* Show the inspector */
WebKitWebInspector *inspector = webkit_web_view_get_inspector (WEBKIT_WEB_VIEW(my_webview));
webkit_web_inspector_show (WEBKIT_WEB_INSPECTOR(inspector));
```

の`webkit_web_load_uri()`は`webkit_web_view_load_uri()`のtypoじゃないかしら。（`_view`が足りない。）

**Comment by ashie** [comment]
https://bugs.webkit.org/show_bug.cgi?id=174767

**Comment by ashie** [comment]
ローカルリポジトリに変更を加えた後、webkit-patchでパッチを送付する。

```
$ ./Tools/Scripts/webkit-patch upload
```

ローカルのリポジトリがgitでも、subversionとgitの両方が入ってないとエラーになる
（リポジトリ形式を検出するため）

対話式に以下の入力を求められる

* バグ番号
* ユーザー名、パスワード
* ChangeLog

**Comment by ashie** [comment]
今回は先にBugを立てたけど、webkit-patchで新しいBugを立てることもできるようだ。
