### ISSUE TITLE
mroonga: Debian stretch の場合のインストール手順がgroongaのままになっている

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#136]
* http://mroonga.org/ja/docs/install/debian.html#stretch-mariadb
* upstream: https://github.com/mroonga/mroonga.github.com

インストール手順の最後でインストールしているパッケージが mroonga ではなく groonga になっている。
すぐ上の jessie の場合は、mariadb-server-10.0-mroonga をインストールしている。

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/commit/6406c2c1b4526042b67a0af2e298475ac0291c1a にて修正したやつ。
