### ISSUE TITLE
Groonga: Dockerイメージの使い方

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#137]
http://groonga.org/ja/docs/install.html に Docker イメージの使い方を書いて欲しい。

* issue tracker や repository の URL
  * https://github.com/groonga/groonga
* 発見した問題についての情報
  * 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)
    * hub.docker.com に groonga/groonga はあるけど、http://groonga.org/ja/docs/install.html に情報がないので最初に到達しづらい
  * 期待する結果
    * http://groonga.org/ja/docs/install.html に Docker イメージの使い方(docker-composeも込み)が書かれていること

**Comment by cosmo0920** [comment]
issueにはないけれど、alpineのapkはGithubで管理されているところがあるようで、 https://github.com/alpinelinux/aports/pulls?q=is%3Apr+is%3Aopen に投げるとapkでインストールできるものが追加できそう （ちゃんと調べてない）

**Comment by cosmo0920** [comment]
ちゃんと追加するならここを読むと良さそう https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by cosmo0920** [comment]
報告しておいた。 https://github.com/groonga/docker/pull/1

**Comment by cosmo0920** [comment]
> http://groonga.org/ja/docs/install.html に Docker イメージの使い方(docker-composeも込み)が書かれていること

これについても対応をしてからクローズしよう。

**Comment by cosmo0920** [comment]
こんな感じ https://github.com/cosmo0920/groonga-docker-compose のものを用意しておけば良さそう。
できればgroonga-httpdをAlpineでも使えるようにしておいたほうがdocker-compose用の設定は簡素になりそう。

**Comment by cosmo0920** [comment]
GroongaのDockerイメージにgroonga-httpdを入れられればdocker-composeでやるべきところが減るので嬉しそう。ということで`--disable-groonga-httpd`オプションをDockerfileから外してみた。
https://github.com/groonga/docker/pull/2

**Comment by cosmo0920** [comment]
ドキュメントを追加するPRを投げたので閉じる。
https://github.com/groonga/groonga/pull/836
