### ISSUE TITLE
PGroonga: Dockerイメージがない

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#139]
https://hub.docker.com/r/groonga/ に pgroonga のイメージがない。

* issue tracker や repository の URL
  * https://github.com/pgroonga
* 発見した問題についての情報
  * 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)
    * オフィシャルに提供されているDockerイメージがない
  * 期待する結果
    * https://hub.docker.com/r/groonga/ に pgroonga のイメージがあること
    * https://pgroonga.github.io/ja/install/ に Docker イメージの使い方が書かれていること

**Comment by cosmo0920** [comment]
CentOS 6で作成しようとしてうまくいかなかったので、Ubuntu Xenialにて作成してみました。

https://github.com/cosmo0920/pgroonga-docker

### ビルド

```bash
$ docker build -t groonga/pgroonga .
```

### 起動

```bash
$ docker run -p 5432:5432 -it groonga/pgroonga
```

### 接続方法

```bash
$ psql -U docker -d docker --password
```

**Comment by okkez** [comment]
もうちょっとがんばってるやつを stretch ベースで書いてます。
https://github.com/clear-code/redmine_full_text_search/tree/add-dockerfiles-for-db

**Comment by cosmo0920** [comment]
お、docker-compose前提で書くとVOLUMEの記述はdocker-compose任せにできるんですね

**Comment by piroor** [comment]
PGroongaのissue trackerに登録しました。

https://github.com/pgroonga/pgroonga/issues/66

以後はそちらで進めるということで、こちらは閉じます。
