### ISSUE TITLE
Mroonga: インストールチェックのところにバージョンを確認する方法を書いて欲しい

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#140]
http://mroonga.org/ja/docs/tutorial/installation_check.html にバージョンを確認する方法が載っていないので、MariaDBの公式リリースなどを利用したときに、MroongaがインストールできているかチェックしてからすぐにMroongaのバージョンを確認したい場合に不便。

情報は http://mroonga.org/ja/docs/reference/server_variables.html#mroonga-version に書かれているもので十分なので、インストールチェックのところにバージョンチェックの方法も書いてあると、自分の使いたいバージョンを使えているのかすぐに確認できるようになってうれしい。

* issue tracker や repository の URL
  * https://github.com/mroonga/mroonga

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/commit/6406c2c1b4526042b67a0af2e298475ac0291c1a で修正していた。

**Comment by kenhys** [comment]
別のissueを閉じるつもりが間違えた。

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/commit/c0ac9aed4e56220eabc96e05c17d8bee2b2c1300 にて追加。
