### ISSUE TITLE
p11-kit: 0.23.10がクロスコンパイルできない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#143]
0.23.3はできる。

https://github.com/p11-glue/p11-kit

こんなエラーになるので`pwd.h`があるかどうかをチェックしてない場合の対応を入れればよさそう。

```text
common/runtime.c:40:17: fatal error: pwd.h: No such file or directory
compilation terminated.
```

**Comment by cosmo0920** [comment]
パッチ付きで報告してみました。
https://bugs.freedesktop.org/show_bug.cgi?id=105517
続きは上記URLで。
