### ISSUE TITLE
fluent-plugin-groonga: table section と mapping section のドキュメントがない

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#144]
* https://github.com/groonga/fluent-plugin-groonga
* http://groonga.org/fluent-plugin-groonga/ja/

**Comment by piroor** [comment]
当該リポジトリのissueに未登録だったので、とりあえず登録しました
https://github.com/groonga/fluent-plugin-groonga/issues/30

**Comment by piroor** [comment]
本体リポジトリの方に登録済みなのでこちらは閉じておきます。
