### ISSUE TITLE
LuaUnit: エラーメッセージ中のエラー発生場所情報抜きで比較できるassertErrorMsgEqualsが欲しい

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#146]
https://github.com/bluebird75/luaunit

http://luaunit.readthedocs.io/en/latest/#assertErrorMsgEquals はエラー発生場所を含めて比較するので使いにくい。 http://luaunit.readthedocs.io/en/latest/#assertErrorMsgContains か http://luaunit.readthedocs.io/en/latest/#assertErrorMsgMatches を使うのがいいよ、と書いているけど、それだと緩くマッチするのでエラーメッセージに余計なものが入っていてもマッチするのがモヤっとする。

`assertErrorMsgContentEquals`みたいな名前の`error_message:gsub("^.+:%d+: ", "")`した結果で比較するバージョンがあるとうれしい。（XMLuaではそういうのを自分で作って使っている。）

**Comment by okkez** [comment]
https://github.com/bluebird75/luaunit/pull/109
