### ISSUE TITLE
Ansible: ドキュメントにtypo

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#147]
http://docs.ansible.com/ansible/latest/intro_installation.html#latest-release-via-yum の

> Ansible will also have RPMs/YUM-repo available at `<https://releases.ansible.com/ansible/rpm/`_.

のリンクのところはなんかおかしくなっていそう。

**Comment by okkez** [comment]
今、見ると↓のようになっていておかしくなっていない。

![image](https://user-images.githubusercontent.com/33111/38015714-993260e2-32a7-11e8-915c-1000966e93f7.png)

https://github.com/ansible/ansible/commit/fc5b74fad2f4f2b29097bca6f54e66d0d42400b5 で直ってた。そしてちょうど5日くらい前に2.5.0がリリースされて直ったものがデプロイされたみたい。
