### ISSUE TITLE
rsyslogのドキュメントにリンク切れがある

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#151]
https://www.rsyslog.com/download/files/windows-agent-manual/configuringmonitorwareagent.html の下の方に http://www.adiscon.com/common/en/concepts/rules-mwa12.php へのリンクがあるが、リンク先ページが存在しない。

**Comment by piroor** [comment]
https://web.archive.org/web/20160816152921/https://www.adiscon.com/common/en/concepts/rules-mwa12.php
2016年まではまだ情報があった模様

**Comment by piroor** [comment]
http://www.monitorware.com/common/en/concepts/rules-mwa12.php
最新の情報はこれのようだ

**Comment by piroor** [comment]
ソースは公開されていませんでしたが、issue報告用のダミーリポジトリは存在するため、そちらに報告しました。
https://github.com/rsyslog/rsyslog-website/issues/46
以後そちらでtrackされるためこちらはcloseします。
