### ISSUE TITLE
luaunit: ドキュメントにちょこちょこ誤記がある

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#154]
https://github.com/clear-code/statistics/issues/80 でフィードバックしようとした時に気がついた点。

### レポジトリ

https://github.com/bluebird75/luaunit/blob/master/doc/index.rst#contributing

### 問題点

> **Contributing**
> ...
> Thank to our continous integration setup with Travis-Ci and AppVeyor, all unit-tests and functional tests are run on Linux, Windows and MacOs, with all versions of Lua. So any *Pull Request* will show immediatly if anything is going unexpected.

* continous -> continuous
* immdiatly -> immediately

> **Typical failures for functional tests**
> ...
> This a good place to start looking if you see failures occuring.

* occuring -> occurring

**Comment by piroor** [comment]
https://github.com/bluebird75/luaunit/pull/107
立てましたのでこちらはcloseします。
