### ISSUE TITLE
libxml2: コメントにゴミがある

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#156]
https://git.gnome.org/browse/libxml2/tree/xpath.c#n5

```c
 *f
```

**Comment by okkez** [comment]
* https://github.com/GNOME/libxml2
* http://xmlsoft.org/bugs.html

gitlab.gnome.org 上にはなかった。

**Comment by okkez** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=795316
