### ISSUE TITLE
Mozilla: コメントにTypo

### ISSUE THREAD

**Issue by cosmo0920** [clear-code/statistics#157]
以下のような情報があると、issueを見た人がスムーズに作業できるはず。

:thought_balloon: 時間がないときは書かなくても :ok:

* issue tracker や repository の URL
  * GitHub 上のプロジェクトは見つけやすいけど、それ以外のプロジェクトは知らないと探すのに時間がかかってしまうため
  * https://dxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxEnv.h#89
* 発見した問題についての情報
  * 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)
     * Very noisy GLContext and GLContextProviderELG
        * GLContextProviderELGではなくGLContextProviderEGLが正しい
  * 再現手順
  * 発生した環境(OSや使用したライブラリーやアプリケーションのバージョンなど)
  * 期待する結果

**Comment by piroor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1457400 Bugzillaに起票したのでこちらは閉じます。
