### ISSUE TITLE
GTK+: ドキュメントにエスケープしすぎな箇所がある

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#158]
https://gitlab.gnome.org/GNOME/gtk

https://developer.gnome.org/gtk3/stable/GtkOverlay.html#id-1.3.7.12.10.4

> The GtkOverlay implementation of the GtkBuildable interface supports placing a child as an overlay by specifying “overlay” as the “type” attribute of a `&lt;child>` element.

`child`の`<`が`&lt;`になっている。

**Comment by kenhys** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=795744 として報告しておいた。
