### ISSUE TITLE
power-assert: unexpected syntax error message

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#16]
No message:

```ruby
      def test_application_xhtml_xml
        assert do
          not @decomposer.target?(create_data("index.html", "application/xhtml+xml"))
        end
      end
 ```

With `<compiled>:1: syntax error, unexpected end-of-input, expecting ')'` message:

```ruby
      def test_application_xhtml_xml
        assert do
          not @decomposer.target?(create_data("index.html",
                                              "application/xhtml+xml"))
        end
      end
 ```

**Comment by piroor** [comment]
@kou Googleで「Ruby power-assert」で検索して最初に出てきたプロジェクトは https://github.com/k-tsj/power_assert でしたが、こちらであっていますでしょうか？

**Comment by kou** [comment]
あっています！

**Comment by piroor** [comment]
度々すみません。これは何のテストをしようとしたときの現象でしょうか？ こちらで条件を整えて再現させてみたいのですが、単純にpower_assertのparserのテストにしてみても再現できませんでした。

**Comment by kou** [comment]
chupa-text-decomposer-htmlです。
https://github.com/ranguba/chupa-text-decomposer-html/blob/master/test/test-html.rb#L47-L51

**Comment by piroor** [comment]
ありがとうございます。調べてみたところ、power_assertは行単位でRubyのコードをパースしているために改行があるとパースエラーになるということのようです。

**Comment by piroor** [comment]
https://github.com/k-tsj/power_assert/issues/20 として報告しました。以後はそちらでトラックしていきます。
