### ISSUE TITLE
chef/bento: Fedora 28のboxイメージが公開されていない

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#166]
以下のような情報があると、issueを見た人がスムーズに作業できるはず。

:thought_balloon: 時間がないときは書かなくても :ok:

* issue tracker や repository の URL

https://github.com/chef/bento/

* 発見した問題についての情報

https://app.vagrantup.com/bento にFedora 28のboxが公開されていない。https://github.com/chef/bento/pull/1035 としてFedora 28対応はマージされたみたいなので、しばらく待てば公開されるのかもしれない。

  * 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)
  * 再現手順
  * 発生した環境(OSや使用したライブラリーやアプリケーションのバージョンなど)
  * 期待する結果

https://app.vagrantup.com/bento でFeodra 28のboxが公開されていて、

```
 config.vm.define :fedora28 do |conf|
    conf.vm.box = "bento/fedora-28"
  end
```

Vagrantfileで上記のようにして、使えるようになっていること。

**Comment by okkez** [comment]
https://app.vagrantup.com/bento/boxes/fedora-28 公開された。
