### ISSUE TITLE
file-roller: 7z-fullをインストールするとzipファイルに互換性がなくなる

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#173]
### URL

http://fileroller.sourceforge.net/

### 手順

* `sudo apt install file-roller`でファイルローラをインストールする
* `sudo apt p7zip-full`で7zをインストールする
* file-rollerを起動して、適当なファイルをドラッグアンドドロップする
* ファイル形式を`zip`にして、`Other Options`から暗号化パスワードを入力する

### 発生する問題

生成されるファイルがAESで暗号化され、Windowsと互換性がなくなってしまう。
（`p7zip-full`がないと互換性のある形で暗号化される）

### 期待する結果

Windowsと互換性のある旧暗号化形式で暗号化される（か少なくとも暗号化方式を選択可能にする）

**Comment by piroor** [comment]
おお、これNautilusじゃなくて別のソフトウェアだったのですね……

**Comment by okkez** [comment]
`-mem=AES128` が[ハードコードされている](https://gitlab.gnome.org/GNOME/file-roller/blob/master/src/fr-command-7z.c#L331)。
マニュアルを確認すると `ZipCrypto` もセットできるようなので、p7zip-full が入っている状態で `-mem=` に与える値を画面からセットできるようになるとよさそう。

**Comment by fujimotos** [comment]
報告済み:  https://gitlab.gnome.org/GNOME/file-roller/merge_requests/1
