### ISSUE TITLE
Firefox: defaultPref("dom.disable_open_during_load", false) が反映されない。Policy EngineでPopupBlocking:Default:falseを設定しても保存されない。

### ISSUE THREAD

**Issue by piroor** [clear-code/statistics#174]
MCDで

```javascript
defaultPref("dom.disable_open_during_load", false);
```

と設定しても、既定値として反映されない。
Policyでも、

```
{
  "policies": {
    "PopupBlocking": {
      "Default": false
    }
  }
}
```

としても`dom.disable_open_during_load`の値は`true`のままだった。

Firefox ESR60 on Windowsで検証した。

**Comment by kenhys** [comment]
* 61.0.1

Linuxの以下のバージョンで追試してみたところ`defaultPref`については再現しなかった。(修正されているような挙動だった。)
(Policyについては未確認)

**Comment by kenhys** [comment]
どのバージョンからというのを調べようとしてLinux版で追試してみたところ、そもそも再現していないような気がする。

`dom.disable_open_during_load`の値はいずれも`false`になった。profileは動作確認ごとに作成しなおしたので混在はないはず。

|version|MCD|PolicyEngine|
|-|-|-|
|60.0esr|not affected|not affected|
|60.0.1esr|not affected|not affected|
|60.0.2esr|not affected|not affected|
|60.1.0esr|not affected|not affected|

**Comment by piroor** [comment]
すみません、この件についてフォローアップを忘れていました。
947838 - Autoconfig's defaultPref() has no effect when distribution.ini exists
https://bugzilla.mozilla.org/show_bug.cgi?id=947838
1466849 - defaultPref not working in autoconfig
https://bugzilla.mozilla.org/show_bug.cgi?id=1466849
後から知ったのですが既にこういう報告があって、これらに該当するケースであった可能性があります。

**Comment by kenhys** [comment]
空のdistribution.iniを置くだけで60.0esrにて再現しました。Firefox 62,63では修正済み、と。

**Comment by kenhys** [comment]
既知っぽいので閉じます。
