### ISSUE TITLE
Remove SEGV for windows-pr on Ruby 2.4 x86

### ISSUE THREAD

**Issue by cosmo0920** [clear-code/statistics#18]
SEGV occurred on Ruby 2.4 and 2.5 trunk when testing windows-pr gem.
Stack trace is here: https://ci.appveyor.com/project/cosmo0920/windows-pr/build/25/job/6j1e8n3mol61fc3f#L33

**Comment by cosmo0920** [comment]
ref: https://bugs.ruby-lang.org/issues/13746

**Comment by okkez** [comment]
https://github.com/cosmo0920/win32-api/pull/31 解決してた。
