### ISSUE TITLE
owncloud の files_external が常に有効なため remember login が常に無効になってしまう

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#183]
ownCloud 10.0.9-1+1.1

* https://github.com/owncloud/core

[files_externalが常に有効になった](https://github.com/owncloud/core/pull/27051)のと[files_externalのバックエンドのいくつかがセッションにパスワードを保存する](https://github.com/owncloud/core/issues/15277)の合わせ技で常に remember login が無効になる状態になっている。

files_external の機能を使用していないときは remember login が有効になるとよいなぁ。

![image](https://user-images.githubusercontent.com/33111/44014531-6da9f0d0-9f07-11e8-8729-04c0f30c95d8.png)

↑のチェックボックスにチェックが入っていないとき、remember login が使えるようになるとよさそう。

**Comment by okkez** [comment]
ログイン時にパスワードを間違えるとパスワードをリセットするためのリンクが表示されるようになった。

**Comment by kou** [comment]
リセットのリンクとremember loginって関係があるんでしたっけ？
リセットするとremember loginできるようになるとか？

**Comment by okkez** [comment]
https://github.com/owncloud/core/pull/33355
