### ISSUE TITLE
OSSystems/meta-browserのfirefoxをESR60に更新する

### ISSUE THREAD

**Issue by cosmo0920** [clear-code/statistics#184]
以下のような情報があると、issueを見た人がスムーズに作業できるはず。

:thought_balloon: 時間がないときは書かなくても :ok:

* issue tracker や repository の URL
  * GitHub 上のプロジェクトは見つけやすいけど、それ以外のプロジェクトは知らないと探すのに時間がかかってしまうため
  * https://github.com/OSSystems/meta-browser
* 発見した問題についての情報
  * 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)
     * meta-browserのupstreamのfirefoxのレシピはまだESR52のため更新したい
  * 再現手順
  * 発生した環境(OSや使用したライブラリーやアプリケーションのバージョンなど)
  * 期待する結果
     * meta-browserのupstreamのfirefoxのレシピがESR60へ更新される

**Comment by ashie** [comment]
以下に途中作業版を置いてある

* 作業用: https://github.com/ashie/meta-browser/tree/firefox-60esr-squashed
* PR用: https://github.com/webdino/meta-browser/tree/update-firefox-to-60esr

いったん[WIP]とかつけてpull requestを送ってから続きをやる（あまり長々と沈黙して進めてないと思われると嫌なので）

**Comment by ashie** [comment]
> いったん[WIP]とかつけてpull requestを送ってから続きをやる（あまり長々と沈黙して進めてないと思われると嫌なので）

以下で進める

https://github.com/OSSystems/meta-browser/pull/160

**Comment by ashie** [comment]
Debianのソース:

* http://cdn-fastly.deb.debian.org/debian/pool/main/f/firefox-esr/
  * http://cdn-fastly.deb.debian.org/debian/pool/main/f/firefox-esr/firefox-esr_60.1.0esr-3.debian.tar.xz

**Comment by cosmo0920** [comment]
そういえばコレ、upstreamにマージされているので閉じておきますね。
