### ISSUE TITLE
ownCloud: カレンダーで繰り返し予定を指定した日の分だけ削除できない（気がする）

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#188]
https://github.com/owncloud/calendar

繰り返し予定のどれかを削除しようとするとその予定だけでなく繰り返し予定すべてが削除されてしまう。

**Comment by myokoym** [comment]
指定した日だけ時間を変更することもできなそう。
（1つの予定の時間を変更すると、すべての予定の時間が変更される）

**Comment by okkez** [comment]
繰り返しの予定を一つだけ削除はできるようになっている。

**Comment by ashie** [comment]
実装されたのは以下辺り (#202 の実装の参考になりそう)

* https://github.com/owncloud/calendar/commit/92bbdf5c2ac9a5dc1bd13003a3f23f7a393ac7ae
* https://github.com/owncloud/calendar/commit/425a6058eaafd6f233aa4f981f5000f52c927111
