### ISSUE TITLE
ownCloud: AndroidのFirefoxでカレンダーを開くとタイムゾーンがUTCになる

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#189]
https://github.com/owncloud/calendar

画面上部に「タイムゾーン(Etc/GMT-9)が不明です，UTCを代替にします。」というポップアップがでる。

Debian GNU/Linux上のFirefoxだとUTCにならないのでもしかしたらAndroidのFirefoxが問題なのかもしれない。

**Comment by ashie** [comment]
最新版でのメッセージは「タイムゾーン(Etc/GMT-9)が不明なため，代わりにUTCを使用します。」になっていた。

**Comment by ashie** [comment]
l10n/ja.js:

```
    "You are in an unknown timezone ({tz}), falling back to UTC" : "タイムゾーン ({tz})が不明なため，代わりにUTCを使用します｡",
```

**Comment by ashie** [comment]
コード的には[この辺](https://github.com/owncloud/calendar/blob/ff9301010426e031b55d179f1b0b2b6da551d2cf/js/app/controllers/calcontroller.js#L158)

**Comment by ashie** [comment]
`TimezoneService`というのは[ical.js](https://github.com/mozilla-comm/ical.js/blob/master/lib/ical/timezone_service.js)の[これ](https://github.com/mozilla-comm/ical.js/blob/master/lib/ical/timezone_service.js)?

**Comment by fujimotos** [comment]
実際に判定しているのは`jstz.determine()`みたいですね。

https://github.com/owncloud/calendar/blob/ff9301010426e031b55d179f1b0b2b6da551d2cf/js/app/service/timezoneService.js#L45

この実際の判定ロジックはこれのようです：

https://github.com/iansinnott/jstz/blob/528b77e9f827ec359cd3f08abe05ff27b597c4d5/jstz.main.js#L383

**Comment by ashie** [comment]
あざす！ようやくみるべき箇所がわかった

**Comment by fujimotos** [comment]
たまたま気がついたんですが、これ nextcloud で報告されているこの問題と同じ問題かもしれないです。

https://github.com/nextcloud/calendar/issues/496

**Comment by ashie** [comment]
既にパッチ書いてる人がいるんですね。

https://github.com/nextcloud/calendar/issues/496#issuecomment-326791894

[パッチのデモページ](https://rawgit.com/Hakuyume/9437ccc66885687a84a41a7f40d87ab8/raw/d094fc9c7be8ecb75e53b23c8add92af3f81a560/jstz-test-wo-intl.html)をAndroid上のFirefoxでアクセスしてみたところ、Asia/Tokyouになっていることを確認できた。

**Comment by ashie** [comment]
https://github.com/nextcloud/calendar/issues/496 では 最終的にはFirefox側のIntlのバグでFirefox 57で直ったとされている。

https://github.com/nextcloud/calendar/issues/496#issuecomment-353824065

**Comment by ashie** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

によるとAndroid版Firefoxでは`Intl.DateTimeFormat`は56以降となっている。

**Comment by ashie** [comment]
こんな感じのを読み込ませると

```html
<html>
<body>
<script>
var region = new Intl.DateTimeFormat();
var options = region.resolvedOptions();
alert(options.timeZone);
</script>
<body>
</html>
```

結果はこうなった

* PC版Firefox 65: `Asia/Tokyo`
* Android版Firefox 65: `Etc/GMT-9`

**Comment by ashie** [comment]
> https://github.com/nextcloud/calendar/issues/496#issuecomment-326791894

手元のownCloudカレンダー（[b74e56e0f1879de50cb73f6de8e71987125c3c5f](https://github.com/owncloud/calendar/tree/b74e56e0f1879de50cb73f6de8e71987125c3c5f)）でも、これで回避できることは確認できた。

**Comment by ashie** [comment]
この辺かな?

* [Bug1487594@bmo](https://bugzilla.mozilla.org/show_bug.cgi?id=1487594)
* [Bug1534160@bmo](https://bugzilla.mozilla.org/show_bug.cgi?id=1534160)
* https://github.com/unicode-org/icu/pull/605

**Comment by ashie** [comment]
これ以上ここでやることは無さそうなのでクローズ
