### ISSUE TITLE
Redmineで作業時間記録済みのissueで時間記録しようとすると紐付かない記録ができる

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#19]
## Problem

1. 作業時間記録済みのissueを選択する
2. 作業時間(x.xx時間)のリンクを選択
3. 画面右の「時間を記録」をクリック
4. xxx/time_entries/new で入力フォームに遷移するがチケット番号の欄が空欄になる

結果として、4で気づかないままだと、どのチケットにも紐付かない作業時間が追加されてしまう。

## Expected

4. でチケットの番号が引き継がれること。

## Actual

4. で自分でチケット番号を埋めないとどのチケットにも紐付かない作業時間が追加されてしまう。

**Comment by piroor** [comment]
これまだ誰も手を着けてないでしょうか？ であれば自分がやってみようと思います

**Comment by piroor** [comment]
バグ報告の前に読む注意事項
http://www.redmine.org/projects/redmine/wiki/Submissions

Redmineのインストール手順
http://www.redmine.org/projects/redmine/wiki/RedmineInstall

既知のバグ一覧
http://www.redmine.org/projects/redmine/issues?query_id=1

**Comment by piroor** [comment]
英語版での表記はタブ「Spend time」→リンク「Log time」→入力欄「Issue」

**Comment by piroor** [comment]
environment:

 * redmine 3.4.1 stable
 * ruby 2.1.5

**Comment by piroor** [comment]
http://blog.enjoyxstudy.com/entry/2015/05/03/000000
https://app.vagrantup.com/onozaty/boxes/redmine-3.4

簡単に使える検証環境として。

**Comment by piroor** [comment]
再現する：

 * Redmine 3.4.2
 * Redmine 3.3.0

**Comment by piroor** [comment]
https://www.redmine.org/issues/26520 として報告しました。以後こちらに書いていきます。

**Comment by piroor** [comment]
https://www.redmine.org/issues/26520#change-80389 で修正されたとのことなので閉じます。
