### ISSUE TITLE
ownCloud: 繰り返しの終わりを日付で指定したい

### ISSUE THREAD

**Issue by myokoym** [clear-code/statistics#193]
https://github.com/owncloud/calendar

**Comment by ashie** [comment]
現在の版(1.6.0)では日付で指定できるようになっていた

たぶんこの辺りのコミットかな https://github.com/owncloud/calendar/commit/425a6058eaafd6f233aa4f981f5000f52c927111

**Comment by ashie** [comment]
社内のownCloudをアップグレードしてからクローズした方がよいだろうか? ということでリオープンしておく。

**Comment by ashie** [comment]
アップグレードされたのでクローズ

**Comment by ashie** [comment]
インターフェースがイケてないので、そこは修正の余地がありそう。
（「毎日」「毎週」「毎月」「毎年」「カスタム」とあるけど、「カスタム」だけで十分そう）
