### ISSUE TITLE
mozillaのwidget/gtk/mozcontainer.hにtypo

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#20]
https://dxr.mozilla.org/mozilla-central/source/widget/gtk/mozcontainer.h#49

```diff
-MOZ_CONAINTER_GET_CLASS
+MOZ_CONTAINER_GET_CLASS
```

**Comment by kenhys** [comment]
フィードバックしておきました。

https://bugzilla.mozilla.org/show_bug.cgi?id=1382142

**Comment by kenhys** [comment]
https://developer.mozilla.org/en-US/docs/Mercurial/Using_Mercurial

hgについてはこのへんをみるとよいという知見。

**Comment by kenhys** [comment]
review+になったあと、Edit bugをクリックして keywords:欄にcheckin-neededを設定して保存するとよいそうだ。
