### ISSUE TITLE
Racc: Ruby 2.6.0devで動かない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#205]
Ruby 2.6.0がリリースされる前になんとかしたい。（Ruby 2.6.0での意図しない非互換ならRuby本体を直しておきたい。）

以下のような情報があると、issueを見た人がスムーズに作業できるはず。

:thought_balloon: 時間がないときは書かなくても :ok:

## issue tracker や repository の URL

https://github.com/tenderlove/racc

### 実際に発生したこと(スタックトレースやログがあればなるべく省略しない)

Ruby 2.5以前ではパースできていた`.ry`をパースすると`unexpected token "$"`になる。

RaccのmasterのTravis CIのビルドでも再現している。

https://travis-ci.org/tenderlove/racc/jobs/456846234#L783

### 再現手順

https://travis-ci.org/tenderlove/racc/jobs/456846234#L783

### 発生した環境(OSや使用したライブラリーやアプリケーションのバージョンなど)

`ruby_ 2.6.0dev (2018-12-05 trunk 66213) [x86_64-linux]`

### 期待する結果

前と同じ結果になる。

**Comment by kou** [comment]
Reported: https://bugs.ruby-lang.org/issues/15389

**Comment by okkez** [comment]
https://bugs.ruby-lang.org/issues/15389 でなおった。
