### ISSUE TITLE
Firefox: 隠し設定経由で低レイヤのログを取得する時、ログローテートできない

### ISSUE THREAD

**Issue by piroor** [clear-code/statistics#22]
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Gecko_Logging
ここに書かれている`rotate:N`が、ログの取得の方法によっては使えない。

ログ出力の設定をpreferencesで指定する場合（MCD用設定ファイルの書式での例）

~~~js:
lockPref("logging.negotiateauth", 5);
lockPref("logging.NTLM", 5);
lockPref("logging.webauthmanager", 5);
lockPref("logging.proxy", 5);
lockPref("logging.nsHttp", 5);
lockPref("logging.config.sync", true);
lockPref("logging.config.add_timestamp", true);
lockPref("logging.config.clear_on_startup", false);
lockPref("logging.config.LOG_FILE","C:\\Users\\Public\\auth.log");
lockPref("logging.config.rotate", 50);
~~~

環境変数を使う方法（バッチファイルの例）

~~~logging.bat:
set MOZ_LOG=timestamp,sync,rotate:50,negotiateauth:5,NTLM:5,webauthmanager:5,proxy:5,nsHttp:5
set MOZ_LOG_FILE=C:\Users\Public\auth-from-bat.log
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
~~~

この2つは意味的に等価であるはずなのだが、`lockPref("logging.config.rotate", 50);`と書いてもログローテートが行われない。

環境変数で与えられたrotateの値を読み取る部分
https://dxr.mozilla.org/mozilla-central/source/xpcom/base/Logging.cpp#210
に相当する処理が、preferencesで指定された設定を解釈する箇所の方
https://dxr.mozilla.org/mozilla-central/source/xpcom/base/LogModulePrefWatcher.cpp#63
には含まれていない。
[1244306 - Use circular buffers for mozilla logging file](https://bugzilla.mozilla.org/show_bug.cgi?id=1244306)（Firefox 51における、ログローテート機能の追加）での実装漏れと思われる。

**Comment by piroor** [comment]
Bugzillaの使い方を簡単に説明しましたが、不明なところがあれば質問よろしく！ @komainu8

**Comment by komainu8** [comment]
問題報告しておきました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1383321

パッチを書きたいので、実装方法について来週、教えていただければと思います。

**Comment by piroor** [comment]
`lockPref`かどうかは重要なポイントではなかったので、説明がちょっとずれてる気がします。via preferences (not environment variable) という所がポイントなので、lockPrefに限らずabout:configで直接設定した場合にも機能することが期待されます。

**Comment by komainu8** [comment]
なるほど。
理解が足りていなかったです。。。

**Comment by cosmo0920** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1383321 won'tfixでクローズされちゃっていますね。
