### ISSUE TITLE
http://chef.github.io/bento/ のリンクが古い

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#23]
### Problem

http://chef.github.io/bento/ の内容が古い。

### Expected

Pre-built Boxesのbento organizationのリンク先が https://atlas.hashicorp.com/bento/ ではなく
https://app.vagrantup.com/bento になっている。

### Actual

* Pre-built Boxesのbento organizationのリンク先がatlas。
* Pre built boxesにリストアップされているbox imageの内容が古い

### フィードバック先

```
Bugs and Issues

Please use GitHub issues to report bugs, features, or other problems.
```

とあるので https://github.com/chef/bento/issues でいいのかもしれない。

最初、 https://github.com/chef/chef-web-docs かと思ったが、どうも docs.chef.ioっぽいのでどうやら違いそう。

**Comment by cosmo0920** [comment]
ちょっと見てみました。 GitHub pagesはgh-pagesブランチにある `index.md` がレンダリングされているようです。

**Comment by cosmo0920** [comment]
投げてみました。 https://github.com/chef/bento/pull/850

**Comment by cosmo0920** [comment]
マージされたのでクローズ。
