### ISSUE TITLE
Redmine をスマホの Google Chrome から見ると検索ボックスにプロジェクトリストが常に表示される

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#25]
* Chrome 59.0.3071.125
* Android 7.0.0; SHV 34 Build/S6010

検索ボックスにプロジェクトリストが白文字でぶら下って表示されてしまう。
タップにも反応するので、とても使い辛い。

**Comment by cosmo0920** [comment]
* Chrome 59.0.3071.125
* Android 7.1.1 の Xperia Performance

では特にそのような現象が起きないのですが、どのような状態になるんでしょうか？

**Comment by okkez** [comment]
キャッシュだったぽい
