### ISSUE TITLE
Wayland（GNOME Shell）上のGimpでスクリーンショットを取ったら真っ黒画面がキャプチャされた

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#26]
環境はUbuntu 17.04。
Fedora 26とかでも起こるかどうか要確認。
そもそもどこの問題だ? どこに報告すれば良い?

**Comment by ashie** [comment]
Fedora 26では取れてるらしい。
PrintScreenとかならUbuntuでも取れる。

**Comment by ashie** [comment]
というわけで報告先はUbuntuっぽい

**Comment by cosmo0920** [comment]
Fedora 26でのGIMPとGNOME on Waylandの組み合わせでは起こらないようです。

**Comment by komainu8** [comment]
Ubuntu 17.10 で確認して問題なければcloseする。

**Comment by kenhys** [comment]
Ubuntu 17.10.1をインストールした環境でapt updateした。動作確認用にgimpをインストール。

```
$ dpkg -l  | grep gimp
ii  gimp                                       2.8.20-1    
```

**Comment by kenhys** [comment]
```
$ env | grep wayland
WAYLAND_DISPLAY=wayland-0
XDG_SESSION_TYPE=wayland
```

**Comment by kenhys** [comment]
File > Create > Screenshot でウィンドウをクリックすると再現した。

![ubuntu1710-gimp-screenshot-dialog](https://user-images.githubusercontent.com/225841/36829106-d4a48512-1d60-11e8-8f8f-7458e7e1c2ab.png)
![ubuntu1710-gimp-screenshot-black](https://user-images.githubusercontent.com/225841/36829107-d4ce18aa-1d60-11e8-8ed1-0219feee2924.png)

**Comment by kenhys** [comment]
報告先はこちらか。

https://bugs.launchpad.net/ubuntu/+source/gimp

screenshot関連でregionについては近い具合があった。ただしUbuntu 13.04+Gimp 2.8.4とバージョンがだいぶ古い。またその後の報告もない。

creating screenshot by grabing a region while using a menu does not work
https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1049851

**Comment by kenhys** [comment]
gimp screenshots are broken
https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1739684

すでに報告されていたみたい。Confirmed扱いになっている。

**Comment by kenhys** [comment]
追加のコメントをフィードバックしておいた。
https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1739684/comments/2

**Comment by kenhys** [comment]
gimp universeっだったか。。。debianでも再現するか確認するのがよさげ。

**Comment by kenhys** [comment]
Debian側でもバグが立てられているやつだった。なのでこれはreopenしたけど閉じよう。

gimp: screenshot does not work with wayland
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880186

Gimp 2.10では修正されているっぽい。

Bug 757687 - Screenshot functionality broken under Wayland 
https://bugzilla.gnome.org/show_bug.cgi?id=757687

**Comment by kenhys** [comment]
https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1739684/comments/4 bugs.launchpadにも追加でコメントしておいた。
