### ISSUE TITLE
railsguidsjp: bin/rails testじゃなくてrake testと書いているところが残っている

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#27]
https://railsguides.jp/testing.html#%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B

> 3.2 テストを実行する
>
> `rake test`コマンドでテストケースを含むファイルを呼び出すことで、簡単にテストを実行できます。

**Comment by komainu8** [comment]
以下のPRでフィードバックしておきました。
https://github.com/yasslab/railsguides.jp/pull/438

**Comment by komainu8** [comment]
マージされたため。Closeします。
