### ISSUE TITLE
mocha でテストを実行すると背景色によってはスタックトレースが見えない

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#29]
Gnome terminal で solarized dark という配色にしているが、mocha で JS のテストを実行するとスタックトレースが見えない。mocha側できちんと背景色を指定すればいいはず。

![screenshot from 2017-07-28 12-58-23](https://user-images.githubusercontent.com/33111/28701917-798b7c4c-7394-11e7-80e4-623478415814.png)

**Comment by piroor** [comment]
http://d.hatena.ne.jp/tatanaideyo/20130122/1358872017 の手順を参考にUbuntu 16.04LTSで設定してみたところ、再現した。

**Comment by piroor** [comment]
組み込みのスキーム「Solarized Dark」
配色「Solarized」
にすると、文字が読めなくなる。パレット左下の色（パレットエントリ9）が背景色と同じなのが原因のようだ。

**Comment by piroor** [comment]
lib/reporters/base.js

```js
exports.colors = {
  pass: 90,
  fail: 31,
  'bright pass': 92,
  'bright fail': 91,
  'bright yellow': 93,
  pending: 36,
  suite: 0,
  'error title': 0,
  'error message': 31,
  'error stack': 90,
  checkmark: 32,
  fast: 90,
  medium: 33,
  slow: 31,
  green: 32,
  light: 90,
  'diff gutter': 90,
  'diff added': 32,
  'diff removed': 31
};
```

ここで90番の色が設定されている箇所が、背景と同じ色なので見えなくなっている。

**Comment by piroor** [comment]
こんな風に強引に背景色を指定してみると、一応読めるようにはなった。

``js
exports.colors = {
  pass: '90m\u001b[101',
  fail: 31,
  'bright pass': 92,
  'bright fail': 91,
  'bright yellow': 93,
  pending: 36,
  suite: 0,
  'error title': 0,
  'error message': 31,
  'error stack': '90m\u001b[101',
  checkmark: 32,
  fast: '90m\u001b[101',
  medium: 33,
  slow: 31,
  green: 32,
  light: '90m\u001b[101',
  'diff gutter': '90m\u001b[101',
  'diff added': 32,
  'diff removed': 331'
};
```

**Comment by piroor** [comment]
issueを検索したら、同じ事で悩んでいる人がいた。

 * [Please change color scheme · Issue #1200 · mochajs/mocha](https://github.com/mochajs/mocha/issues/1200 "Please change color scheme · Issue #1200 · mochajs/mocha")
 * [Much of the color output is invisible with solarized terminal theme · Issue #802 · mochajs/mocha](https://github.com/mochajs/mocha/issues/802 "Much of the color output is invisible with solarized terminal theme · Issue #802 · mochajs/mocha")
 * [Allow custom color scheme · Issue #590 · mochajs/mocha](https://github.com/mochajs/mocha/issues/590 "Allow custom color scheme · Issue #590 · mochajs/mocha")
 * [Solarized · Issue #122 · mochajs/mocha](https://github.com/mochajs/mocha/issues/122 "Solarized · Issue #122 · mochajs/mocha")

**Comment by cosmo0920** [comment]
ざっと目を通しましたがなんだかやり取りが噛み合ってないですね。
Solarizedを使っている人はSolarizedサイコーって感じですが、
mochaのメンテナはSolarizedの色は変なのでは、と言っているので説得するの難しそうですね。
ここまでざっと読んだ個人的な所感ですが、色の彩度とか色相とかそういうので論理的に攻めるしかなさそう。

**Comment by piroor** [comment]
ありがとうございます、議論がどういうことになってるのか長すぎてまだ把握できてませんでした……

**Comment by piroor** [comment]
https://github.com/mochajs/mocha/pull/2946, https://github.com/mochajs/mocha/issues/2945 として報告したためこちらは閉じます。

**Comment by cosmo0920** [comment]
CLA(Contributor License Agreement)もサインしておくと良いと思いますよ！
