### ISSUE TITLE
lintian: debian/controlのuploadersにリストされていてもNMUの警告がでる

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#3]
## 事前準備

* unstableの環境を用意する

## 確認方法

1. 適当なパッケージをapt sourceで取得して debian/controlのUploaders:に自分をリストアップ
2. パッケージをビルドする
3. lintianでチェックする 警告がでるはず(うろ覚え)

## フィードバック先

bugs.d.oにメールを投げる

**Comment by komainu8** [comment]
6月は手が空かないので、7月からやってみます!

**Comment by kenhys** [comment]
なんか、debian/changelogのメールアドレスじゃなくて名前でマッチさせている予感がしてきた。

```

 -- Kentaro Hayashi <hayashi@clear-code.com>  Thu, 29 Jun 2017 18:47:17 +0900                  

```

**Comment by kenhys** [comment]
補足説明を書いておこうと思ったが、これもう再現しなくなっているっぽいので閉じる。
