### ISSUE TITLE
debian-9.1-i386のimagesが公開されていない

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#31]
## Problem

Debian 9.1がリリースされたけど対応するboxが公開されていない。

## Expected

~~bento/debian-9.1~~とbento/debian-9.1-i386をVagrantfileに記述すると利用できる

## Actual

https://github.com/chef/bento
 debian-9.1-amd64.jsonとdebian-9.1-i386.jsonがコミットされているけど、Vagrant Cloudで公開されていない。https://app.vagrantup.com/bento

## Action

https://github.com/chef/bento/issues に **debian-9.1-i386** boxイメージ公開してくださいというissueをたてる

**Comment by kenhys** [comment]
amd64は公開されているけど、i386はまだのようなので、issueの説明を更新。

**Comment by okkez** [comment]
https://github.com/chef/bento/issues/892
