### ISSUE TITLE
about:configを無効化する方法が無い

### ISSUE THREAD

**Issue by piroor** [clear-code/statistics#33]
https://bugzilla.mozilla.org/show_bug.cgi?id=580349
バグは立っていて、パッチも出ていたのだが、自動テストが準備できなかったためかずっと止まっている。
XUL廃止後はこれが必要になる。

**Comment by kenhys** [comment]
内容を確認してみた。

* パッチというのは https://bugzilla.mozilla.org/show_bug.cgi?id=580349#c33 で言及されている
https://bugzilla.mozilla.org/attachment.cgi?id=591600 のこと。toolkit/components/viewconfig/content/config.js で about:configの要素をいじって、about:configをブロックするようにしている。いちおうまだmozilla-centralにはxulのコードは残っているがパッチがまだそのままあたるかは未確認。
* テストについては https://bugzilla.mozilla.org/show_bug.cgi?id=580349#c36 と https://bugzilla.mozilla.org/show_bug.cgi?id=580349#c39 とに参考になりそうなリンクの言及がある
  * https://developer.mozilla.org/en/Browser_chrome_tests
  *  ~http://mxr.mozilla.org/mozilla-central/source/toolkit/crashreporter/test/browser/browser_aboutCrashes.js~ => https://dxr.mozilla.org/mozilla-central/source/toolkit/crashreporter/test/browser/browser_aboutCrashes.js
* https://bugzilla.mozilla.org/show_bug.cgi?id=580349#c46 では @piroor さんが https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides の拡張? して `"chrome_url_overrides":{"config":"..."}` みたいに書けるようにしてみてはどうかという提案をしている

方向性としては既存のパッチが取り込まれるように頑張るか(ただしXUL) or chrome url overridesを拡張してカスタマイズできるようにするかという状況のようだ。

**Comment by kenhys** [comment]
そもそもこのパッチまだ有効なんだっけ？と確認してみた。

```
% patch -p1 < ../580349.patch
can't find file to patch at input line 9
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|# HG changeset patch
|# Parent edf8075b0333a0ed7be2d77b1fd06bc87ca7bdec
|# User aceman <acelists@atlas.sk>
|Bug 580349 - lock user access to about:config when general.blockAboutConfig pref is set; ui-r=limi
|
|diff --git a/modules/libpref/src/init/all.js b/modules/libpref/src/init/all.js
|--- a/modules/libpref/src/init/all.js
|+++ b/modules/libpref/src/init/all.js
--------------------------
File to patch: modules/libpref/init/all.js
patching file modules/libpref/init/all.js
Hunk #1 FAILED at 50.
1 out of 1 hunk FAILED -- saving rejects to file modules/libpref/init/all.js.rej
patching file toolkit/components/viewconfig/content/config.js
Hunk #1 FAILED at 355.
1 out of 1 hunk FAILED -- saving rejects to file toolkit/components/viewconfig/content/config.js.rej
patching file toolkit/components/viewconfig/content/config.xul
Hunk #1 FAILED at 90.
1 out of 1 hunk FAILED -- saving rejects to file toolkit/components/viewconfig/content/config.xul.rej
patching file toolkit/locales/en-US/chrome/global/config.dtd
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file toolkit/locales/en-US/chrome/global/config.dtd.rej
```

**Comment by kenhys** [comment]
元のパッチを更新してみた。まだ動作確認はとれていない。

[580349.refresh.patch.txt](https://github.com/clear-code/statistics/files/1508865/580349.refresh.patch.txt)

**Comment by kenhys** [comment]
about:preferences まわりを参考にテストを用意するとよいのではと @piroor さんにアドバイスをもらった

たぶんこのへんをみるとよさそうである。
https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/in-content/tests

**Comment by kenhys** [comment]
追加するのはこっちが妥当そう。

https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/about

**Comment by kenhys** [comment]
* パッチは更新する必要があった
  * https://github.com/clear-code/statistics/issues/33#issuecomment-347440115
* テストを追加する先がわかった
  * https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/about
* テストの書き方は about:supportにならうとよさそうということがわかった
  * https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/about/browser_aboutSupport.js

**Comment by kenhys** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=580349#c50 にて更新したパッチ(テストを含む)を投げておいた。
このissueについては一旦閉じることにしよう。
