### ISSUE TITLE
Zulip: 検索キーワードとして日本語を入力したときに「Search for ...」がでてこないときがある

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#38]
検索ボックスのところででてくる候補ウィンドウ？みたいなやつのところ。

**Comment by okkez** [comment]
「Search for」が出ていない状態でアルファベットで検索しようとタイプし始めると出る。
アルファベットを入力した後、入力を全部消してから日本語の漢字やひらがなで検索すると、「Search for」は出たまま。

「Search for」が出ていない状態で、ひらがなで検索しようとタイプし始めてもアルファベットで入力したときと異なり「Search for」は出ない。
「Search for」が出ていない状態でも、漢字で検索しようとすると「Seach for」は出る。

:thought_balloon: ただしuim-skkを使っている。

**Comment by cosmo0920** [comment]
macOSの日本語入力でインライン入力をしている時でも出ていないですね。
Search forが出ていない時に入力を確定させても検索が開始されません。

**Comment by fujimotos** [comment]
Zulip（より正確にはbootstrapのtypeaheadモジュール）は`keydown`イベントを使って
候補ウィンドウを制御しているみたいです。

* 問題は、IME変換中のキーボードイベントの扱いはブラウザ依存という点で、
  実際、FirefoxだとIME変換中は`keydown`イベントが一切発火しません。
* この結果、日本語IMEを使ってると、ユーザーのキー入力をZulipがうまく検知できず、
  候補ウィンドウまわりが想定と異なる動きをしてしまうようです。

これと同じ理由で、コメント入力のストリーム／トピック欄のサジェストも、
日本語入力だと現状うまく動きません。

**Comment by piroor** [comment]
https://www.fxsitecompat.com/ja/docs/2018/keydown-and-keyup-events-will-soon-be-fired-during-ime-composition/
Firefox側の仕様が変わって、日本語入力中もkeydownが発生するように変わるようです。
なので、この問題は自然解決するとみていいかと。

**Comment by piroor** [comment]
Nightly 62.0a1 on Ubuntu, with IIIMF ATOK X3で検証した所、日本語入力中でもインクリメンタルサーチが行われるようになっていました。
ただし、変換の確定操作のEnterキーが検索開始のEnterキーとして取り扱われてしまい、入力の途中なのに検索されてしまって困ります。

**Comment by piroor** [comment]
https://github.com/clear-code/statistics/issues/38#issuecomment-389135795 の問題については https://github.com/zulip/zulip/issues/9396 で報告しました。
このIssueは閉じて良いでしょうか？

**Comment by okkez** [comment]
報告したなら閉じていいのではー。ということで閉じます。
