### ISSUE TITLE
PGroongaの&@~が導入されたバージョンが間違っている

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#39]
## Problem

https://pgroonga.github.io/reference/operators/query-v2.html に記載されている &@~ がいつから使えるかのバージョンが誤っている。

## Expected

正しくはSince 1.2.2.
根拠: https://pgroonga.github.io/ja/news/ の1.2.2のエントリ。

## Actual

実際にはSince 1.2.0

## Action

https://pgroonga.github.io/ へのフィードバック。

**Comment by komainu8** [comment]
以下のpullrequestでフィードバックしました。
https://github.com/pgroonga/pgroonga.github.io/pull/32

**Comment by okkez** [comment]
フィードバックしたら close してください。
