### ISSUE TITLE
zulip: PGroongaを使っていてもOR検索ができない

### ISSUE THREAD

**Issue by piroor** [clear-code/statistics#4]
https://github.com/zulip/zulip/blob/master/static/js/filter.js#L226 ここらへんを起点に調べると分かりそう

**Comment by piroor** [comment]
https://github.com/zulip/zulip/blob/master/static/js/filter.js#L244 ここで、`operator:...`以外の形式のトークンはすべて検索語句として取り扱っている。

**Comment by piroor** [comment]
パース結果のoperatorsが https://github.com/zulip/zulip/blob/master/static/js/narrow.js#L48 に渡される。

**Comment by piroor** [comment]
https://github.com/zulip/zulip/blob/master/static/js/filter.js#L194 ここで`toLowerCase()`されている。

**Comment by piroor** [comment]
https://github.com/zulip/zulip/blob/master/static/js/filter.js#L191ここの`toLowerCase()`を外したら、PGroongaでOR検索になった。

**Comment by piroor** [comment]
何か必要があってtoLowerCase()しているのかと思ったが、chat.zulip.orgで同じ変更をオンメモリで反映してみても別に支障はなかった。
（FirefoxのWebコンソールで以下を実行すると試せる）

~~~
var k = Filter; Filter.canonicalize_term = function(a){var b=a.negated,c=a.operator;a=a.operand;b||(b=!1);c=k.canonicalize_operator(c);switch(c){case "has":a=a.replace(/s$/,"");break;case "stream":a=stream_data.get_name(a);break;case "topic":break;case "sender":case "pm-with":a=a.toString().toLowerCase();"me"===a&&(a=people.my_current_email());break;case "search":a=a.toString().replace(/[\u201c\u201d]/g,
'"');break;default:a=a.toString().toLowerCase()}return{negated:b,operator:c,operand:a}};
~~~

**Comment by ashie** [comment]
問題解決は報告先で
