### ISSUE TITLE
Mroongaのリファレンスマニュアルに類似文書検索について書く

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#42]
https://www.slideshare.net/kou/groongaseminar201708 を参考にして書く。インデックスの作り方や tokenizer に TokenMecab を指定する方法などを書く。

**Comment by kenhys** [comment]
期待されるのはこのあたりのスライドの内容。

https://image.slidesharecdn.com/groonga-seminar-2017-08-mroonga-and-pgroonga-170731154902/95/mysqlpostgresqlgroonga-45-638.jpg?cb=1501516230

**Comment by kenhys** [comment]
チュートリアルとして類似文書検索について触れるのがよさそう。ドキュメントをおこしてみよう。

**Comment by kenhys** [comment]
https://github.com/kenhys/mroonga/commit/b75802b6b1f5df7c0f16b094ada4f17aff8ab0e9 書きかけのドキュメントをコミット。

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/pull/199 として成果をとりこんだので閉じる。
