### ISSUE TITLE
Debian GNU/Linux sid: GDM: "GNOME on Xorg" uses Xwayland

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#44]
ログイン時に"GNOME on Xorg"を指定してログインしてもXwaylandを使ったGNOMEを起動する。

`/etc/gdm3/daemon.conf`を以下のようにするとXorgを使う。

```text
[daemon]
# Uncoment the line below to force the login screen to use Xorg
WaylandEnable=false
```

**Comment by kenhys** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872316 としてフィードバックしておきました。
