### ISSUE TITLE
browser-api-demoでロケーションバーの文字列が[object Object]になる

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#46]
該当箇所は以下

https://github.com/mdn/browser-api-demo/blob/master/main.js#L112

仕様変更か何かがあって追従できていないとか?
以下に正しい使用例がある:

https://developer.mozilla.org/ja/docs/Web/Events/mozbrowserlocationchange

**Comment by ashie** [comment]
以下に修正は用意してある。

https://github.com/ashie/browser-api-demo/commit/aaac931117b681c0a29cc749389676e034504a95

**Comment by cosmo0920** [comment]
https://github.com/mdn/browser-api-demo/pull/3 として報告しました。
