### ISSUE TITLE
WordPress: How to format list of contirubutors isn't documented

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#47]
https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#readme%c2%a0header-information

に

> The line for Contributors is a case sensitive list of all WordPress.org usernames who have contributed to the code.

と書いているけど「list」はどのようにフォーマットすればよいか（スペース区切り？カンマ区切り？とか）書いていないので複数人指定するときに困る。

https://plugins.svn.wordpress.org/akismet/trunk/readme.txt を見るとカンマ区切りっぽい。

**Comment by kenhys** [comment]
https://meta.trac.wordpress.org/ticket/3197 にてフィードバックしておいた。
