### ISSUE TITLE
Debian 8.9 のboxイメージが公開されていない

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#49]
## Problem

Debian 8.9がリリースされたけど対応するboxが公開されていない。

## Expected

bento/debian-8.9 とbento/debian-8.9-i386をVagrantfileに記述すると利用できる

## Actual

https://github.com/chef/bento
 debian-8.9-amd64.jsonとdebian-8.9-i386.jsonがコミットされているけど、Vagrant Cloudで公開されていない。https://app.vagrantup.com/bento

## Action

https://github.com/chef/bento/issues にboxイメージ公開してくださいというissueをたてる

**Comment by okkez** [comment]
今、確認したら debian-8.9, debian-9.1 ともに公開されてた。
