### ISSUE TITLE
Firefox WebExtensions API: browser.tabs.move()の戻り値がドキュメントの説明と異なる

### ISSUE THREAD

**Issue by piroor** [clear-code/statistics#50]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/move
これによると、このメソッドの第1引数は移動対象のタブのIDを示す単一の整数値、もしくは整数値の配列を受け取れる。
また、戻り値は単一のIDを受け取った場合は単一の`tabs.Tab`、IDの配列を受け取った場合は`tabs.Tab`の配列であることになっている。

実際には、単一のIDを渡した場合でも戻り値が常に配列になっている様子だった。
testcase:

```javascript
async function testMoveSingleTabInOneWindow() {
  var window = await browser.windows.create();
  var tab = await browser.tabs.create({
                    windowId: window.id,
                    url: 'about:blank?newtab',
                  });
  var movedTab = await browser.tabs.move(tab.id, {
                         index: 0,
                         windowId: window.id
                       });
  browser.windows.remove(window.id);

  if (!Array.isArray(movedTab))
    console.log('testMoveSingleTabInOneWindow SUCCESS');
  else
    console.log('testMoveSingleTabInOneWindow FAIL');
}

async function testMoveSingleTabAcrossWindows() {
  var window1 = await browser.windows.create();
  var window2 = await browser.windows.create();
  var tab = await browser.tabs.create({
                    windowId: window1.id,
                    url: 'about:blank?newtab',
                  });
  var movedTab = await browser.tabs.move(tab.id, {
                         index: 1,
                         windowId: window2.id
                       });
  browser.windows.remove(window1.id);
  browser.windows.remove(window2.id);

  if (!Array.isArray(movedTab))
    console.log('testMoveSingleTabInOneWindow SUCCESS');
  else
    console.log('testMoveSingleTabInOneWindow FAIL');
}

testMoveSingleTabInOneWindow();
testMoveSingleTabAcrossWindows();
```

ウィンドウをまたぐ移動かどうかに関わらず発生している。

**Comment by piroor** [comment]
上記テストケースを試す方法

 * `manifest.json`の`permissions`に`tabs`を含む状態にして、`about:debugging`から一時的なアドオンとして読み込む。
 * 読み込まれたmanifest.jsonに対応する項目が表示されるので、「Debugging」リンクをクリックする。
 * デバッガが起動するので、コンソールで上記スクリプトを実行する。

**Comment by cosmo0920** [comment]
> A Promise that will be fulfilled with a tabs.Tab object or an array of tabs.Tab objects, containing details about the moved tabs. If no tabs were moved (for example, because you tried to move an unpinned tab before a pinned tab) this will be an empty array. 

とあって、対象のタブがなかった場合に空の配列になるようなので一つの時だけ `tabs.Tab` オブジェクトになるのはなんだか不自然に思います。 `a tabs.Tab object or an array of tabs` とあるので、 `tabs.Tab` オブジェクトか配列かのどちらかであれば仕様を満たしそうですが。。。

**Comment by cosmo0920** [comment]
Chromeの場合はどうなるんでしょうか？

**Comment by piroor** [comment]
Chromeと挙動が違う部分はparity-chromeか何かのタグが付けられて修正の対象になるはずなので、いずれにせよ実装かドキュメントかのどちらかは間違いと言えそうです。

と思ったのですが、

> 対象のタブがなかった場合に空の配列になるようなので一つの時だけ tabs.Tab オブジェクトになるのはなんだか不自然に思います

「A Promise that will be fulfilled with "a tabs.Tab object" or "an array of tabs.Tab objects"」とあって、戻り値は「単一のtabs.Tab」または「（0個以上の）tabs.Tabの配列」という読み方をしたのは間違ってないと思うのですが、よくよく読み返してみると、自分が思っていた「第1引数が単一のIDだったら戻り値も単一のtabs.Tabになる」という期待される動作の説明はどこにも書いてないですね。

**Comment by piroor** [comment]
Chrome用テストケース

```javascript
function testMoveSingleTabInOneWindow() {
  chrome.windows.create(window => {
    chrome.tabs.create({
      windowId: window.id,
      url: 'about:blank?newtab',
    }, tab => {
      chrome.tabs.move(tab.id, {
        index: 0,
        windowId: window.id
      }, movedTab => {
        chrome.windows.remove(window.id);
        if (!Array.isArray(movedTab))
          console.log('testMoveSingleTabInOneWindow SUCCESS');
        else
          console.log('testMoveSingleTabInOneWindow FAIL');
      });
    });
  });
}

function testMoveSingleTabAcrossWindows() {
  chrome.windows.create(window1 => {
    chrome.windows.create(window2 => {
      chrome.tabs.create({
        windowId: window1.id,
        url: 'about:blank?newtab',
      }, tab => {
        chrome.tabs.move(tab.id, {
          index: 0,
          windowId: window2.id
        }, movedTab => {
          chrome.windows.remove(window1.id);
          chrome.windows.remove(window2.id);
          if (!Array.isArray(movedTab))
            console.log('testMoveSingleTabInOneWindow SUCCESS');
          else
            console.log('testMoveSingleTabInOneWindow FAIL');
        });
      });
    });
  });
}

testMoveSingleTabInOneWindow();
testMoveSingleTabAcrossWindows();
```

こちらはどちらもSUCCESSなので、Firefoxの動作が間違っていると言えそうです。

**Comment by piroor** [comment]
参考：FirefoxとChromeとで動作が違ってＣｈｒｏｍｅに合わせたというbugの例 https://bugzilla.mozilla.org/show_bug.cgi?id=1366290

**Comment by ashie** [comment]
上記にはついてないけど、Bugzillaで(keywordに?)parity chromeが付いている場合はChromeと違う動作の場合には修正対象となるらしい。

**Comment by ashie** [comment]
コードがどこにあるのかはまだ確認していないとのこと

**Comment by ashie** [comment]
バグを立てるときのProduct,Componentは以下が良さそう
Product: toolkit
Component: WebExtensions: Compatibility

**Comment by ashie** [comment]
Firefoxでのテストコード実行方法

* about:debuggingを開く
* 「アドオンのデバッグを有効化」のチェックを入れる
* タブ関連の拡張の「デバッグ」をクリックする
    * コードを実行するのにタブ関連の権限が必要なので、すでに権限を持っているタブ関連の拡張でテストをするのが楽
* リモートデバッガが起動する
* `location.href`とかやると、本当に権限を持っているか確認できる
* 上記のテストコードを貼り付ける
* テストが実行される

**Comment by ashie** [comment]
Google Chromeでのテストコード実行方法

* Firefoxと同じようにタブ関連の権限を持つ拡張でテストするのが手っ取り早い
    * ここではSidewise Tree Style Tabsを使うことにする
* メニュー → その他のツール → 拡張機能
* デベロッパーモードのチェックを入れる
* Sidewise Tree Style Tabsのビューの検証のbackground.htmlをクリック
* Developper Toolsが起動するので、「Console」を開く
* テストコードを貼り付ける
* テストが実行される

**Comment by ashie** [comment]
59.0a1 (2017-12-29) での結果

```
testMoveSingleTabInOneWindow FAIL 
Loading failed for the <script> with source “moz-extension://024ac528-f0a3-40cf-b943-370dc920d028/common/tree/constants.js”.  sidebar.html:8
Error: Invalid window ID: 56  ext-tabs-base.js
Error: Invalid tab ID: 5 ext-browser.js
TypeError: tab is null[Learn More]  handlers.js:131:7
testMoveSingleTabInOneWindow FAIL 
Loading failed for the <script> with source “moz-extension://024ac528-f0a3-40cf-b943-370dc920d028/common/tree/constants.js”.  sidebar.html:8
Error: Invalid tab ID: 7 ext-browser.js
Error: Invalid window ID: 58  ext-tabs-base.js
Error: Invalid tab ID: 7 ext-browser.js
```

**Comment by ashie** [comment]
報告した。続きはそちらで。

https://bugzilla.mozilla.org/show_bug.cgi?id=1427346
