### ISSUE TITLE
packages.groonga.orgのnightlyパッケージの作成が止まっている

### ISSUE THREAD

**Issue by cosmo0920** [clear-code/statistics#52]
nightlyパッケージが作成されているとWindows向けのパッケージのビルドをnightlyで試すことができるので問題に気付きやすい。

**Comment by kenhys** [comment]
別ホストで生成とアップロードをするようにしてみました。
ひとまずはこれでどうでしょう。

**Comment by kenhys** [comment]
フィードバックするなら、 https://github.com/groonga/packages.groonga.org でしょうか。
@cosmo0920

**Comment by cosmo0920** [comment]
問題が解決してしまったので今回はこのままで良いと思います。次回からIssueを報告するようにしましょう。
