### ISSUE TITLE
strasky/gecko-devが--enable-default-toolkit=cairo-gtk3でビルドできない

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#53]
[StranskyのWayland版Firefox](https://github.com/stransky/gecko-dev)が`--enable-default-toolkit=cairo-gtk3`でビルドできない。
このブランチは`--enable-default-toolkit=cairo-gtk3-wayland`しか想定してないため。
とはいえ一応`#ifdef`で切り分けようとはしているし、いずれもう少し整理して本流にマージ
されるとうれしいので、まずはビルドできるようにしておいた方が良い。

**Comment by cosmo0920** [comment]
Red HatのBugzillaに報告済み。https://bugzilla.redhat.com/show_bug.cgi?id=1495147
