### ISSUE TITLE
Go: syscall.CREATE_BREAKAWAY_FROM_JOB isn't defined

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#55]
ここらへんに定義するといいのかしら。
https://github.com/golang/sys/blob/master/windows/types_windows.go#L161-L162 

名前と値のリスト： https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx

**Comment by kenhys** [comment]
https://github.com/golang/sys にならって、https://github.com/golang/go/issues/22801 x/sys/windows: prefixをつけて報告しておいた。
