### ISSUE TITLE
Redmine: wikiにファイルが添付されていてもわかりづらい

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#56]
# Problem

Redmineのwikiにファイルが添付されているかがぱっと見にはわかりづらい。

# Expected

ファイルの初期表示で添付の有無がわかる

# Actual

Wikiの初期表示

![redmine-wiki-file](https://user-images.githubusercontent.com/225841/30192048-d2a5b368-947f-11e7-867f-3d76ee0b57f2.png)

ファイルの→アイコンをクリックしてはじめて有無がわかる

![redmine-wiki-no-attachment](https://user-images.githubusercontent.com/225841/30192060-e1e5384e-947f-11e7-9e45-d31c66325335.png)

**Comment by okkez** [comment]
表示だけの問題なら https://github.com/onozaty/redmine-view-customize を入れてカスタマイズすれば解決しそう。本体に入れたいなら、view-customizeで検証してからどうしたいか決めて提案するとよいのでは。

**Comment by kenhys** [comment]
なるほど、こういったプラグインがあるのですね。参考になりました！

**Comment by okkez** [comment]
http://www.redmine.org/issues/27090

パッチきてた。Redmine4 には入るらしい。

**Comment by okkez** [comment]
アップストリームで対応済みなので閉じる。
