### ISSUE TITLE
debian: Debian live with xfceの起動時設定画面の項目の統一

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#58]
## Problem

debian-live-9.1.0-amd64-xfce.isoで起動したときのローカライズの設定項目に違和感

## Expected

表記がLocalisationではなく、Localizationであること
ただし、イギリス英語に統一されているんであればLocalisationで問題ないはず。

## Action

他の箇所がイギリス英語で統一されているか確認して、
アメリカ英語で統一されているなら
https://www.debian.org/devel/debian-live/ Debian Liveプロジェクト？にフィードバックする

**Comment by okkez** [comment]
どこの画面にこれが出てるのかわからないので、調べられない。
ローカライズの設定項目ってどこー？？

**Comment by kenhys** [comment]
Graphial Installerを試したときの話だったように思うのだけど、試してみたら再現しなかった。
勘違いだったのかもしれないので閉じる。
