### ISSUE TITLE
debian: liveイメージで起動したときしばらく放置するとlock画面をunlockできない

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#59]
## Problem

debian-live-9.1.0-amd64-xfce.isoで起動し、しばらく放置するとunlockできなくなる。

## Expected

lock画面をunlockできる

## Action

https://www.debian.org/devel/debian-live/ Debian liveプロジェクト？もしくはそれ関連のbugとしてフィードバックする。

**Comment by okkez** [comment]
https://stackoverflow.com/questions/30842216/debian-8-live-cd-what-is-the-standard-login-and-password

user/live でロック解除できる。

:thought_balloon: 以前調べた記憶があったので、また調べた。

**Comment by okkez** [comment]
debian-live-9.3.0-amd64-xfce.iso で確認したけど、少なくとも Debian 8 の頃から user/live でいけるみたい。
