### ISSUE TITLE
fluent-plugin-mail: マルチノードの説明のtypo

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#61]
## Problem

https://github.com/u-ichi/fluent-plugin-mail/blob/master/README.md にtypoがある

## Expected

 `MulatiNode's syslog check` ではなくて `MultiNode's syslog check` だと思う。

## Action

https://github.com/u-ichi/fluent-plugin-mail へとPR.

**Comment by komainu8** [comment]
以下でPRしました。
https://github.com/u-ichi/fluent-plugin-mail/pull/40

**Comment by komainu8** [comment]
マージされたのでCloseします。
