### ISSUE TITLE
rvm:  Unsupported operator '9'.

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#65]
## Problem

`rvm install ruby-2.4` をunstable環境で実行すると `Unsupported operator '9'.`と赤色で表示される。
(実際にはそのままインストールが進むので実害はないけれど。。。)

環境: Debian unstable & rvm get head

## Expected

`Unsupported operator '9'.`が表示されないこと。

## Note

rvmの実装みてないけど、たぶんjessieまでしか念頭になさそう。

**Comment by okkez** [comment]
https://github.com/rvm/rvm/blob/1.29.3/scripts/functions/detect_systems/debian_codenames#L6

最新リリースっぽいのだと stretch 対応意識されてるっぽい。master HEADだと buster も対応されてるっぽい。

**Comment by kenhys** [comment]
対応されているようなので閉じる。
