### ISSUE TITLE
Pango: <a href="...">...</a>に対応する

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#68]
https://developer.gnome.org/pango/stable/PangoMarkupFormat.html に`<a>`と`<span href="...">`サポートを追加して、PDF生成時にリンクを作れるようにしたい。

cairo 1.15.4から`cairo_tag_begin()`と`CAIRO_TAG_LINK`いうAPIが追加されていて、リンク情報を描画できるようになっている。 https://cgit.freedesktop.org/cairo/tree/test/pdf-tagged-text.c

**Comment by okkez** [comment]
pango/pango-markup.c の `span_parse_func` に様々な属性に対応する分岐があるのでその辺を弄れば `<span href="...">` の対応はできそう。
これに対応するテストは tests/markup-parse.c にある。
tests/markups/ 以下に入力と期待する結果が入っているので、それらを追加すればテストも書けるはず。

`<a>` は `a_parse_func` というのを pango-markup.c に追加して `start_element_handler` の switch-case のあたりで `parse_func = a_parse_func` みたいにやれば追加できそう。

**Comment by okkez** [comment]
cairo を直接使って PDF にリンクを埋め込むのはできた。

https://gist.github.com/okkez/32bc15544caf0750ff5d5e11db57ddaf

**Comment by okkez** [comment]
それっぽいのができたけど、PDFに埋め込むところの動作確認がまだ。
https://github.com/okkez/pango/tree/support-link

**Comment by okkez** [comment]
追加した `<span href="..."></span>` と `<a href="..."></a>` がパースできた。

**Comment by okkez** [comment]
`<a href="...">...</a>` を下線付きで表示することができたけど、`cairo_tag_begin` はどこで使えばいいんだろう？cairo_context をセットしないといけないので pango-markup.c の中では使えなくて、たぶん `pango_markup_parse` でパースした結果を自分で見てなんとかしないといけない気がする。

**Comment by okkez** [comment]
GitHub上で見つけたサンプルコードに手を加えてマークアップしたものをPDF出力できるようにしたサンプル。
https://gist.github.com/okkez/5debbc744b2838f54133fb355f954705

**Comment by okkez** [comment]
ちょっとわからなくなったので、今できているパッチを出して相談してみることにした。

https://bugzilla.gnome.org/show_bug.cgi?id=794754
