### ISSUE TITLE
mruby-onig-regexpのRegexp#matchがブロックを無視する

### ISSUE THREAD

**Issue by komainu8** [clear-code/statistics#75]
ブロックを指定したときはマッチしたときだけブロックを実行するというのが、Rubyの`Regexp#match`の動作。
http://rurema.clear-code.com/2.4.0/method/Regexp/i/match.html

mruby-onig-regexpのRegexp#matchはブロックを無視するようなので、上記の動作ができない。

**Comment by okkez** [comment]
とりあえず、手元ではできた。

* https://github.com/iij/mruby-regexp-pcre
* https://github.com/masamitsu-murase/mruby-hs-regexp

mrubyで使えるregexpの実装としては、↑もあるけど、あまり活発にメンテナンスされてない気がするけど、実装は超簡単にできるので対応するか。。。

**Comment by okkez** [comment]
https://github.com/mattn/mruby-onig-regexp/pull/78
