### ISSUE TITLE
Redmineで3レベル以上の箇条書きでも2インデントでよくしたい

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#8]
OK

```markdown
* 1
  * 2     
     * 3
```

NG

```markdown
*  1
   * 2
     * 3
```

**Comment by okkez** [comment]
lib/redmine/wiki_formatting/ 以下に新しいフォーマットとして commonmark を追加してあげればよさそう。
ただし commonmarker だと redcarpet と変換結果が異なる場合やサポートしている記法に差があるので、注意が必要。
commonmarker と redcarpet で互換性が怪しいので、新しいフォーマットを追加して様子を見る。
最初はプラグインでやって、調子が良さそうなら本家に提案するという流れにするとよさそう。

**Comment by okkez** [comment]
作り始めた。
https://github.com/okkez/redmine_common_mark

**Comment by okkez** [comment]
動くのができた。

**Comment by okkez** [comment]
deployed.
