### ISSUE TITLE
mozilla-central: VideoData::CreateAndCopyIntoTextureClient()の宣言だけが残っている

### ISSUE THREAD

**Issue by ashie** [clear-code/statistics#81]
`CreateAndCopyIntoTextureClient()`が現在のコードでは実体が存在しないのに宣言だけが残っているような気がする。

https://dxr.mozilla.org/mozilla-central/source/dom/media/MediaData.h#515

昔はGonk回りで実体らしきものがあったような雰囲気（以下でも実体は見当たらないがGonk関連で使っているところがある）

https://dxr.mozilla.org/mozilla-esr52/search?q=CreateAndCopyIntoTextureClient&redirect=true

**Comment by ashie** [comment]
Firefox 51辺りで一時的に存在していたが

* https://github.com/mozilla/gecko-dev/commit/f323872778630
* https://bugzilla.mozilla.org/show_bug.cgi?id=1292032

恐らくGonkのコードを消す時に実体だけ消された模様。ESR52では既に存在しない。
追加するときに宣言の方だけ`#ifdef MOZ_OMX_DECODER`で囲い忘れていたため、消すときも忘れられたままになったということだろう。

実体を消すときのコミットはまだ見つけられていない。

**Comment by piroor** [comment]
削除されたコードの、いつ削除されたかの探し方ということになる？

手元にmozilla-esr52をcloneした物があったので、

 1. `hg tags`でFirefox 51のリリース時のタグ名を調べる。
 2. `hg update -C FIREFOX_51_0_RELEASE`でその時点のソースを取り出す。
 3. `grep -r CreateAndCopyIntoTextureClient dom/media/`で関数が書かれていたファイルを特定する。dom/media/MediaData.cppである事が分かった。
 4. https://hg.mozilla.org/mozilla-central/filelog/cad9c9573579698c223b4b6cb53ca723cd930ad2/dom/media/MediaData.cpp でコミットログを見る
 5. `d084c1f34802created 2016-10-18 18:10 -0400 pushed 2016-10-20 14:47 +0000 | Ehsan Akhgari | Ehsan Akhgari - Bug 1311214 - Remove b2g OMX encoder/decoder; r=cpearce`というのが見つかった。
     https://hg.mozilla.org/mozilla-central/diff/d084c1f34802/dom/media/MediaData.cpp で関数本体が削除されている事を確認できた。

以上の事から、このコミットでの削除し忘れだと分かった。

**Comment by piroor** [comment]
導入時のコミットは、hg.mozilla.orgだと https://hg.mozilla.org/mozilla-central/diff/906df3f2cce7/dom/media/MediaData.cpp だった。

**Comment by ashie** [comment]
Bugzillaのバグを立てるときのパラメータに迷ったら、元のバグを参照すれば良い。

**Comment by piroor** [comment]
パッチの提出前に、ビルドが通る事くらいは確認しておく。
WindowsでのMozilla Centralのビルド環境を整えるということになる。

**Comment by piroor** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites の手順に従って作業を進めていると、`./mach bootstrap`の実行時に、Artifact Buildにするかどうかを訊ねられた。
Artifact BuildはC++のコンポーネントのビルドを省略する物。
今回のようにC++のコンポーネントに変更を加える場面では適していないため、Artifact Buildでない選択肢を選ぶ。

**Comment by ashie** [comment]
パッチ作るためにわちゃわちゃやっている間に他の人が修正してしまった（笑）ので、とりあえず本issueは閉じておきます

**Comment by piroor** [comment]
ビルド環境の置き場所をどうするか聞かれる。既定値は `c:/Users/(username)/.mozbuild`になっている。
特に変える理由もないので、Yes（1）を選択する。

次に、Mercurialを独自改造版に変えるか聞かれる。 
これもYes（1）を選択する。

**Comment by piroor** [comment]
Will you be submitting commits to Mozilla (Yn)? と聞かれるが、これはMozillaの社員でコミット権を持っている人向けの話なので、nを選択する。

**Comment by piroor** [comment]
`./mach build`すると、古い`mozconfig`の内容が邪魔をしてconfigureに失敗した。`mozconfig`を削除したところ、configureは通るようになった。
ただ、今度は別のエラーで止まるようになった。（midlという実行ファイルが見つからない）
