### ISSUE TITLE
Gnumeric: NULLでもOKなので(nullable)がついていない引数がある

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#82]
たとえば、`workable_view_new_from_input()`の`optional_fmt`。 https://git.gnome.org/browse/gnumeric/tree/src/workbook-view.c#n1207

あれ、これ、仮引数名が `optional_format`でドキュメントの方の名前が`optional_fmt`だからここから直さないといけなそう。

他にもいろいろ`NULL`でもOKなのにドキュメントに`(nullable)`がついていないのがありそう。そもそもGnumericの中で`(nullable)`を書いているのがないかも。

**Comment by piroor** [comment]
@okkez さんに教わりながら取り組もうとしています。現時点で分かった事：

 * GLibは（C++を使えない、あるいは使いたくない場面で）C言語でオブジェクト指向をやるための便利ライブラリである。
 * GnumericはC言語で開発されていて、GLib、GTKをライブラリとして使用している。
 * 問題の箇所は、コードだけが変更されてコメントの変更が行われなかった結果のように見える。
 * `g_return_val_if_fail`は、与えられた条件が満たされなかった時にその場で指定の値をreturnするためのマクロである。この場面ではいわゆるearly returnのために使われている。
 * `optional_fmt`は`NULL`またはファイルオープナー（何？）である事が期待されている。それ以外が渡されたらこの関数は即座に`NULL`をreturnする。
 * `g_return_val_if_fail`でのチェックの後で、改めて`NULL`の場合の処理が書かれている。
 * 「ドキュメントに`(nullable)`が付いている」状態とは、ここに記載されているような状態を指している。 https://wiki.gnome.org/Projects/GObjectIntrospection/Annotations#parameter_part

**Comment by piroor** [comment]
@kou さしあたって不具合として報告しようと思っていますが、この問題が問題として認識された文脈が分からないため、どのように問題を報告すればよいかがピンと来なくて、つまづいています。

 * 単にドキュメントやコードを流し読みしていて不整合を見付けたので報告する、という場面なのか
 * 何かの必要があって調査の過程で不整合を見付けたので報告する、という場面なのか
 * 修正すると誰がどのように嬉しいのか（修正されないとどう困るのか、現在進行形でどう困っているのか）

このあたりの文脈を教えていただくことはできますでしょうか？

**Comment by kou** [comment]
Rubyバインディング https://github.com/ruby-gnome2/ruby-gnome2/tree/master/gnumeric で`NULL`で大丈夫だから省略可能な引数でも、`NULL`じゃない（Rubyレベルだと`nil`じゃない）値を用意しないといけなくて使いにくい（あるいは、`NULL`を指定するのが妥当なところでも`NULL`を指定できない）、という文脈です。

**Comment by piroor** [comment]
ありがとうございます。gem install gnumericでインストールして状況を把握してみたいと思います。

**Comment by piroor** [comment]
https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gnumeric/test/test-convert.rb
この内容をirbで実行してみた。openerがnilでも特に問題が起こらずCSV出力できた。

**Comment by piroor** [comment]
これは「めんどくさいやりかた」の方だった。
https://lazka.github.io/pgi-docs/Gnm-1.12/mapping.html
https://lazka.github.io/pgi-docs/Gnm-1.12/index.html
https://packages.debian.org/testing/gir1.2-gnumeric
期待されているのは、`Gnm::WorkbookView.new_from_input`一発でもっと簡単にできること、か。

**Comment by piroor** [comment]
girとはGObject Introspectionの略。
http://www.clear-code.com/blog/2013/12/16.html

関数を`Gnm::WorkbookView.new_from_input`にマップするための情報はすでに存在している。
https://lazka.github.io/pgi-docs/Gnm-1.12/classes/WorkbookView.html#Gnm.WorkbookView.new_from_input

**Comment by piroor** [comment]
ここからやることの方向性

 1. Gnumericのソースを編集してビルド
 2. GObject Introspecitionの情報を生成
 3. 本当にバインディングの挙動が直っているか確認
 4. Gnumericにフィードバック

**Comment by piroor** [comment]
ソースコードを入手 https://git.gnome.org/browse/gnumeric/

```
$ git clone https://git.gnome.org/browse/gnumeric
```

**Comment by piroor** [comment]
変更してみた

```
diff --git a/src/workbook-view.c b/src/workbook-view.c
index 518a710..b1f35bc 100644
--- a/src/workbook-view.c
+++ b/src/workbook-view.c
@@ -1099,7 +1099,7 @@ wb_view_save_to_uri (WorkbookView *wbv, GOFileSaver const *fs,
  * wb_view_save_as:
  * @wbv: Workbook View
  * @fs: GOFileSaver object
- * @uri: URI to save as.
+ * @uri: (nullable): URI to save as.
  * @cc:
  *
  * Saves @wbv and workbook it's attached to into @uri file using
@@ -1204,7 +1204,8 @@ wb_view_save (WorkbookView *wbv, GOCmdContext *context)
 /**
  * workbook_view_new_from_input:
  * @input: #GsfInput to read data from.
- * @optional_format: Optional GOFileOpener
+ * @optional_uri: Optional URI for file
+ * @optional_format: (nullable): Optional GOFileOpener
  * @io_context: Optional context to display errors.
  * @optional_encoding: Optional encoding for GOFileOpener that understand it
  *
@@ -1307,7 +1308,7 @@ workbook_view_new_from_input (GsfInput *input,
 
 /**
  * workbook_view_new_from_uri:
- * @uri: URI for file
+ * @uri: (nullable): URI for file
  * @optional_format: Optional GOFileOpener
  * @io_context: Optional context to display errors.
  * @optional_encoding: Optional encoding for GOFileOpener that understand it
```

**Comment by piroor** [comment]
./autoconf.sh を実行するとgtkdocize, bisonが無いといわれた。`sudo apt install gtk-doc-tools bison`でインストールした。

再実行すると、依存関係が満たされていないという事でエラーになった。

```
configure: error: Package requirements (
	libgoffice-0.10	>= 0.10.38
	libgsf-1		>= 1.14.33
	libxml-2.0		>= 2.4.12
 
	gtk+-3.0		>= 3.8.7
) were not met:

Requested 'libgoffice-0.10 >= 0.10.38' but version of libGOffice is 0.10.28

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBSPREADSHEET_CFLAGS
and LIBSPREADSHEET_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

実行環境がUbuntu 16.04なのでパッケージが古い。
okkyzさんに確認してもらうと、Debian Sidでもlibgoffice 0.10.35なのでいずれにせよlibgofficeのビルドは必要だとのこと。

**Comment by cosmo0920** [comment]
単純に依存関係にあるライブラリが欲しいのであれば、Linuxbrewのgofficeが 0.10.38なので使えそうです。
https://github.com/Linuxbrew/homebrew-core/blob/2bbf1da9c9baa33efd564e4db2a472f7aa908aa6/Formula/goffice.rb

**Comment by piroor** [comment]
Linuxbrewというのを初めて知りました。。。

vagrantでDebian Sidの仮想環境を用意して作業中。
どうせ今回限りの環境なのでグローバルに入れてしまうという方向で。

```
$ sudo apt-get build-dep gnumeric goffice
$ git clone https://git.gnome.org/browse/goffice
$ cd goffice
$ ./autogen.sh
$ make
$ sudo make install
$ cd ..
$ git clone https://git.gnome.org/browse/gnumeric
$ cd gnumeric
$ ./autogen.sh
```

ここまでは無事に進んだ。

**Comment by piroor** [comment]
`sudo make install`が失敗する。

```
...
Making install in doc
make[1]: Entering directory '/home/cezmi/gnumeric/doc'
Makefile:1342: *** missing separator.  Stop.
make[1]: Leaving directory '/home/cezmi/gnumeric/doc'
make: *** [Makefile:657: install-recursive] Error 1
```

**Comment by piroor** [comment]
`sudo apt install yelp-tools`で解決する可能性があると教えてもらったので試した。
パッケージをインストールすると処理は先に進んだが、別のエラーになった。

```
Error: Could not merge translations:
xmlDocGetRootElement() failed
make[2]: *** [Makefile:1409: cs/cs.stamp] Error 1
make[2]: Leaving directory '/home/cezmi/gnumeric/doc'
make[1]: *** [Makefile:662: all-recursive] Error 1
make[1]: Leaving directory '/home/cezmi/gnumeric'
make: *** [Makefile:519: all] Error 2
```

**Comment by cosmo0920** [comment]
ちょっと見てみると、 `g_return_val_if_fail` のアサーションで `NULL` チェックしていない引数に関しては `(nullable):` アノーテーションが付けられそうな気がしました！

**Comment by piroor** [comment]
docのビルドはこけるがsrcのビルドは成功しており、今回はsrcのビルドだけでよいのではという指摘を頂いた。

**Comment by piroor** [comment]
`doc/cs`以下のビルドでエラーになっているので、`doc/cs` を別の場所に移動して、Makefileで`cs`を含んでいる箇所を書き換えてみたら、`make`も`make install`も成功するようになった。

**Comment by piroor** [comment]
試しにirbで動かしてみようとしているのだがエラーになる。

```
$ irb
irb(main):001:0> require "gnumeric"
=> true
irb(main):002:0> Gnm::WorkbookView.new_from_input
Unable to init server: Could not connect: Connection refused
Gtk::InitError: failed to initialize GTK+
	from /var/lib/gems/2.3.0/gems/gtk3-3.2.1/lib/gtk3/loader.rb:44:in `call_init_function'
	from /var/lib/gems/2.3.0/gems/gtk3-3.2.1/lib/gtk3/loader.rb:31:in `pre_load'
	from /var/lib/gems/2.3.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:38:in `load'
	from /var/lib/gems/2.3.0/gems/gtk3-3.2.1/lib/gtk3/loader.rb:26:in `load'
	from /var/lib/gems/2.3.0/gems/gtk3-3.2.1/lib/gtk3.rb:66:in `init'
	from /var/lib/gems/2.3.0/gems/goffice-3.2.1/lib/goffice.rb:52:in `init'
	from /var/lib/gems/2.3.0/gems/gnumeric-3.2.1/lib/gnm.rb:51:in `init'
	from /var/lib/gems/2.3.0/gems/gnumeric-3.2.1/lib/gnm.rb:38:in `const_missing'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
irb(main):003:0>
```

**Comment by piroor** [comment]
クリーンな環境として作成したFedora Workstation 27でやり直し。

 1. dnfで入れたgnumericとgemで入れたgnumericの組み合わせで動作を確かめる
 2. ソースからビルドした無改造のgnumericとgemで入れたgnumericの組み合わせで動作を確かめる
 3. ソースからビルドした改変済みのgnumericとgemで入れたgnumericの組み合わせで動作を確かめる

セットアップ

```
# dnf install git ruby ruby-devel gnumeric libgsf-devel
# dnf groupinstall development-tools rpm-development-tools c-development
# gem install rake
# gem install gnumeric
```

`dnf install libgsf-devel`と`gem install rake`は`gnumeric`に必要。
`libgsf-devel`はRakefileにfedora向けの定義が無い事が原因か？

**Comment by piroor** [comment]
ruby-gnome2が依存しているwebkitgtkがfedoraでは公式リポジトリから削除されているそうなので、ここの手順を見ながらビルド
https://ask.fedoraproject.org/en/question/117590/upgrade-to-fedora-27-no-webkitgtk-what-are-my-options/

**Comment by fujimotos** [comment]
アップストリームに報告済みです：

https://bugzilla.gnome.org/show_bug.cgi?id=794112

以後の進展についてはこちらをフォローください。

**Comment by fujimotos** [comment]
以下、補足です：

* 上記チケットで提示したパッチで ruby-gnome2/gnumeric 配下のテストが通るようになるところまで確認してます。
* なお、nullableを付した関数は`workbook_view_new_from_uri()`ですが、これでWorkbookView.newの第二引数にnullが渡せるようになります。
* ちなみに`workbook_view_new_from_input()`の方に直接nullableをつけるとエラーになってしまうようです。
