### ISSUE TITLE
GOffice: NULLでも大丈夫なやつの引数のドキュメントに(nullable)がついていない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#83]

**Comment by cosmo0920** [comment]
GOFileSaverについては報告してみました。

**Comment by cosmo0920** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=793684

**Comment by cosmo0920** [comment]
治ったらしい https://bugzilla.gnome.org/show_bug.cgi?id=793684
