### ISSUE TITLE
libxml2: エンコーディング検出ルーチンがHTML5の<meta charset="ENCODING">に対応していない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#84]
`<meta http-equiv="Content-Type" content="text/html; charset=ENCODING">`には対応している。

**Comment by komainu8** [comment]
既に、「Add HTML parser support for HTML5 meta charset encoding declaration」という変更が入っていたが、この対応で修正されているのは、`htmlCheckEncodingDirect`と`htmlCheckEncoding`のみなので、対応漏れの可能性がある。

**Comment by komainu8** [comment]
`htmlFindEncoding`を`<meta charset="ENCODING">`の形式に対応するように変更しようとしたが、`htmlFindEncoding`を呼び出しているコードに以下のようなコメントがあった。

```
Humm this is bad, do an automatic flow conversion
```

ゆくゆくは、ここのコードは、無くしたいような雰囲気を感じる。周りの方に相談したところ、まず、`htmlFindEncoding`がHTML5の`<meta charset="ENCODING">`に対応していないことをupstreamへ報告して、修正したほうがよいかどうかを聞いてみてはどうかということになった。

したがって、まず問題報告をしてみる。

**Comment by komainu8** [comment]
問題報告するにしても、具体的にどう修正するつもりなのかを示す必要がありそうだったので、修正パッチを投げることにした。

**Comment by komainu8** [comment]
以下で修正パッチを投げた。
https://bugzilla.gnome.org/show_bug.cgi?id=791376

**Comment by komainu8** [comment]
パッチを投げたので、Closeします。
