### ISSUE TITLE
MariaDB: コメントに複数のタイポがある

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#85]
`onion -> union` だと思う：

https://github.com/MariaDB/server/blob/10.3/sql/sql_lex.h#L745

`versioniong -> versioning`

https://github.com/MariaDB/server/blob/10.3/mysys/lf_alloc-pin.c#L164

**Comment by ashie** [comment]
コントリビューションガイド https://mariadb.com/kb/en/library/contributing-code/

**Comment by ashie** [comment]
GitHubにMariaDBのリポジトリがあった https://github.com/MariaDB/server

**Comment by ashie** [comment]
でもマージされてるのも結構あるが、これはどういうこと?
今回のようなtypo修正でマージされてるのもある https://github.com/MariaDB/server/pull/500

**Comment by ashie** [comment]
ということで、今回は敢えて PR を試してみる。
ダメだったら改めてjiraに投げる。

**Comment by ashie** [comment]
投げてみた。

https://github.com/MariaDB/server/pull/512
