### ISSUE TITLE
pgroonga.github.io: `custom`を動詞として使っている

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#86]
pgroonga.github.ioのドキュメント全般の中で`custom`を動詞として使っている。
例えばこんな感じ：

> See How to custom token filters for token filters details.
> https://github.com/pgroonga/pgroonga.github.io/blob/master/reference/create-index-using-pgroonga.md

customは名詞／形容詞なので、全体的にcustomizeに改めるべき。

**Comment by cosmo0920** [comment]
フィードバックしました。 https://github.com/pgroonga/pgroonga.github.io/pull/37
目立った箇所は置き換えたつもりです。

**Comment by cosmo0920** [comment]
フィードバックした後のやりとりは上記のURLのpull requestでやることにしましょう。
