### ISSUE TITLE
firefox: firefox screenshotsで「ページ全体を保存」してからの「ダウンロード」に失敗

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#89]
# Problem

Firefox screenshotsを使ってスクリーンショットを保存後にダウンロードできない。

# Expected

すべてのスレッドかどうかにかかわらずスクリーンショットを保存、ダウンロードできる。

# Actual

https://crash-stats.mozilla.com/report/index/703f8cbb-d694-446c-9c6a-aea660171212#allthreads
ですべてのスレッドを表示した状態でスクリーンショットを保存した後に、ダウンロードできない。
すべてのスレッドを表示していなければダウンロードできる。

![image](https://user-images.githubusercontent.com/225841/33877794-d18287ee-df6c-11e7-938d-fb7179c4b39d.png)

**Comment by okkez** [comment]
crash not found になって確認できない。

**Comment by okkez** [comment]
twitter で長めにTLを表示してから試すと再現した。

**Comment by okkez** [comment]
「ダウンロード」と「コピー」はできなかったけど、「保存」はできた。

**Comment by okkez** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1439822

登録した。
