### ISSUE TITLE
libxml2に実行時にバージョンを取得するAPIが欲しい

### ISSUE THREAD

**Issue by komainu8** [clear-code/statistics#91]
マクロでバージョンを取得する方法はあるが、それだとビルド時でないとバージョンが取得できないため、FFIでlibxml2を使う場合にバージョンが取得できない。

そのため、関数を実行したら使っているライブラリーのバージョンを取得できるようなAPIが欲しい。

**Comment by komainu8** [comment]
libxml2のglobals.cに以下のような関数があった。
これは使えないだろうか？

```c
const char * *
__xmlParserVersion(void) {
    if (IS_MAIN_THREAD)
        return (&xmlParserVersion);
    else
        return (&xmlGetGlobalState()->xmlParserVersion);
}
```

**Comment by komainu8** [comment]
以下のように、`__xmlParserVersion`をFFIで呼び出して、libxml2のバージョンを取得できた。

```lua
local ffi = require("ffi")

local loaded, xml2 = pcall(ffi.load, "xml2")
if not loaded then
  xml2 = ffi.load("libxml2.so.2")
end

ffi.cdef[[
    const char * *__xmlParserVersion(void);
]]

print(ffi.string(xml2.__xmlParserVersion()[0]))
```
結果
```
% luajit test.lua
20904
```

20904は 2.9.4 を表す。
自分の環境に入っているlibxml2は以下のバージョンなので、上記の結果と一致する。

```
ii  libxml2:amd64                                  2.9.4+dfsg1-2.2+deb9u1       amd64                        GNOME XML library
```

**Comment by komainu8** [comment]
したがって、現状用意されているAPIでlibxml2のバージョンを取得できる。

**Comment by ashie** [comment]
なんでアンスコプレフィックスついてるんだろう?と思って調べてみた。

libxml/globals.h

```
XMLPUBFUN const char * * XMLCALL __xmlParserVersion(void);
#ifdef LIBXML_THREAD_ENABLED
#define xmlParserVersion \
(*(__xmlParserVersion()))
#else
XMLPUBVAR const char * xmlParserVersion;
#endif
```

APIと言えるのかな?

**Comment by ashie** [comment]
http://xmlsoft.org/html/libxml-globals.html#xmlInitializeGlobalState

xmlInitializeGlobalState()ってやつで取れる構造体にxmlParserVersionというのが入ってるけど、これって使えないのかな?

**Comment by ashie** [comment]
`__xmlParserVersion()`はアンスコプレフィックスが付いてるので、あまりオフィシャルに公開してる感じじゃない雰囲気を感じるし、コンパイル条件によっては消えちゃう奴だと思ったので。

**Comment by komainu8** [comment]
なるほど。GlobalStateが使えるかどうか見てみます。

**Comment by kou** [comment]
普通は`xmlParserVersion()`を使ってね、というAPIだと思うので、↓みたいに、`__xmlParserVersion()`があればそれを使って、なかったら`xmlParserVersion`を使う、とすればよいと思います。

https://github.com/clear-code/xmlua/blob/master/xmlua/libxml2.lua#L24-L36

**Comment by komainu8** [comment]
既に存在するAPIでlibxml2に実行時にバージョンを取得できるため、closeします。
