### ISSUE TITLE
libxml2: htmlCreatePushParserCtxt()がhtmlParserCtxt::pushTabを初期化しない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#93]
`htmlCreatePushParserCtxt()`が`ctxt::pushTab`を初期化せずに`NULL`のままにするので、これで作った`ctxt`を使って`xmlParseChunk()`をして、要素を処理しようとすると`nameNsPush()`で`ctxt::pushTab`を触ってクラッシュする。

`xmlCreatePushParserCtxt()`みたいに`ctxt::pushTab`を初期化しないといけない気がするんだけど、たぶん、変更を忘れているんだと思う。

**Comment by komainu8** [comment]
以下で問題報告とパッチを送付しました。
https://bugzilla.gnome.org/show_bug.cgi?id=791618
