### ISSUE TITLE
libxml2: htmlCreatePushParserCtxt()がhtmlParserCtxt::spaceTabを初期化しない 

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#94]
`htmlCreatePushParserCtxt()`が`htmlParserCtxt::spaceTab`と`spaceMax`を初期化せず、`spaceTab`は`NULL`で、`spaceMax`は`0`のままになる。この状態で`xmlParseChunk()`でテキストデータをパースすると、`spacePush()`で`spaceTab`を初期化しようとするんだけど、`spaceMax`が`0`なので`0`バイトの領域を`xmlRealloc()`しようとして`free()`扱いになって`NULL`が返ってきてしまって`xmlErrMemory()`でメモリーエラー扱いになってしまう。

`xmlInitParserCtxt()`では`spaceTab`を初期化しているので、`htmlInitParserCtxt()`でも同じように初期化するといいと思うんだけど、たぶん、更新忘れな気がする。

**Comment by komainu8** [comment]
以下で問題報告と修正したパッチを送付しました。
https://bugzilla.gnome.org/show_bug.cgi?id=791739
