### ISSUE TITLE
NetworkMananger-l2tp: Gateway IDを指定するとsecretsにIPsec先のアドレスではなくGateway IDを使ってしまう

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#96]
`/etc/ipsec.d/nm-l2tp-ipsec-${UUID}.secrets`に生成されるファイルの内容が

```text
${SERVER_IP_ADDRESS}: PSK "${PRE_SHARED_KEY}"
```

じゃなくて

```text
${GATEWAY_ID}: PSK "${PRE_SHARED_KEY}"
```

になってしまい、IPsecを設定をしているときに設定した`${PRE_SHARED_KEY}`が使われない。（`${GATEWAY_ID}`じゃなくて`${SERVER_IP_ADDRESS}`で`${PRE_SHARED_KEY}`を検索するため。）

これでいける気がする。

```patch
diff --git a/src/nm-l2tp-service.c b/src/nm-l2tp-service.c
index e901958..3fcc064 100644
--- a/src/nm-l2tp-service.c
+++ b/src/nm-l2tp-service.c
@@ -711,11 +711,7 @@ nm_l2tp_config_write (NML2tpPlugin *plugin,
 				write_config_option (fd, "%%any ");
 			}
 			/* With PSK, only IP addresses are allowed as IDs */
-			if (inet_pton(AF_INET, value, &naddr)) {
-				write_config_option (fd, "%s ", value);
-			} else {
-				write_config_option (fd, "%%any ");
-			}
+			write_config_option (fd, "%s ", priv->saddr);
 		}
 
 		value = nm_setting_vpn_get_data_item (s_vpn, NM_L2TP_KEY_IPSEC_PSK);
```

**Comment by ashie** [comment]
元のソースはこれ?

* https://github.com/nm-l2tp/network-manager-l2tp/blob/master/src/nm-l2tp-service.c#L715

**Comment by kou** [comment]
これ、このパッチじゃいけないことは確認していました。

IKEv1じゃなくてIKEv2というのを使いたかったんですが、今調べてみるとhttps://github.com/nm-l2tp/network-manager-l2tp/issues/62 というのがあって、そこにはnetwork-manager-l2tpじゃなくてnetwork-manager-strongswanを使ってね、とありました。

なので、これはもう閉じていいです！
