### ISSUE TITLE
Kibana: 最新版バイナリのダウンロードリンクがつながらない

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#97]
[公式サイト](https://www.elastic.co/start) のv6.1.0のリンクが不通。

![2017-12-21-125746_1169x291_scrot](https://user-images.githubusercontent.com/8974561/34240009-a11bf9b2-e64e-11e7-9a97-e1dedef9246a.png)

上のスクショのうち「Linux 64-bit」のリンク先が今はこうなっているが：

>  https://artifacts.elastic.co/downloads/kibana/kibana-6.1-0-linux-x86_64.tar.gz

正しくはこうじゃないだろうか：

> https://artifacts.elastic.co/downloads/kibana/kibana-6.1.0-linux-x86_64.tar.gz

この報告先が不明なので要調査。

**Comment by okkez** [comment]
https://github.com/elastic/kibana に書いてあるフォーラムかgithub issueがよさそう。

**Comment by cosmo0920** [comment]
フォーラムに投げておきました。 https://discuss.elastic.co/t/could-not-download-kibana-6-1-0-package-for-linux-64-bit-in-official-website/112742

**Comment by cosmo0920** [comment]
以降のやりとりはそちらで。
