### ISSUE TITLE
td-agent: インストールメッセージにタイポがある

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#98]
インストールスクリプト https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh の実行時に表示されるユーザーメッセージに誤記がある。

```bash
$ sh install-ubuntu-xenial-td-agent-3.sh
Intallation completed. Happy Logging!

NOTE: In case you need any of these:
  1) security tested binary with a clear life cycle management
  2) advanced monitoring and management
  3) support SLA
Please check Fluentd Enterprise (https://fluentd.treasuredata.com/).
```

1. 初っ端の "Intallation" は "Installation" に直す。
2. エンタプライズ版のURL https://fluentd.treasuredata.com にアクセスするとリダイレクトされる。
    * 移転先は https://www.treasuredata.com/fluentd/ の模様。
    * なので、このURLもついでに直しておくとよいかも。

**Comment by ashie** [comment]
このファイルがどこで管理されているのかがわからない

**Comment by ashie** [comment]
裏技で修正された
